<div class="row" id="access">
	<div class="col-sm-12">
		<h2 class="titleText">Instrumento de Adesão</h2>
		<h4><span class="subTitText"> INSTRUMENTO DE FORMALIZAÇÃO PARA PARTICIPAR DA BIBLIOTECA DIGITAL BRASILEIRA DE TESES E DISSERTAÇÕES (BDTD)</span></h4>
		<p class="text">
			Para participar da Biblioteca Digital Brasileira de Teses e Dissertações (BDTD) é necessário que a instituição formalize o processo de integração à Rede BDTD, por meio da assinatura do Instrumento de Adesão. Para isso, solicita-se que a instituição entre em contato com a Equipe BDTD, seguindo o fluxo de processo para participar da BDTD (ver <a href="<?=$this->url('content-page', ['page' => 'participate']) ?>">Como participar? </a> ).
		</p>	
	</div>
</div>