<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
<style type="text/css">
	
	.iconRed{
		color: red;		
	}

	.iconGreen{
		color: #0a630a;		
	}

	.disable{
		display: none;
	}

	.active{
		display: '';
	}

</style>
<div class="row" id="faqs">
	<div class="col-sm-12">
		<h2 class="titleText">FAQs</h2>
		<h4><span class="subTitText"> PERGUNTAS FREQUENTES SOBRE A BIBLIOTECA DIGITAL BRASILEIRA DE TESES E DISSERTAÇÕES (BDTD)</span></h4>
		<p class="text">
			<ol>			
				<li>
					O que é a Biblioteca Digital Brasileira de Teses e Dissertações (BDTD)?   					
					<!--a id="descBdtd" href="#" onclick="showDesc(this);"><span class="glyphicon glyphicon-plus-sign fa-1x" style="color: #0a630a;"></a>
					<span style=" display: none;" class="descBdtd">
						O Sistema de Publicação Eletrônica de Teses e Dissertações (TEDE) é uma solução tecnológica desenvolvida pelo IBICT e repassada gratuitamente às instituições de ensino e pesquisa para que possam gerenciar suas teses e dissertações.		

						glyphicon glyphicon-minus-sign				

					</span-->
				</li>
				<li>
					O que é o Sistema de Publicação Eletrônica de Teses e Dissertações (TEDE)?
					<a id="descTede" href="#" onclick="showDesc(this);"> <span class="glyphicon glyphicon-plus-sign fa-1x iconGreen" ></span></a>
					<span class="disable">
						O Sistema de Publicação Eletrônica de Teses e Dissertações (TEDE) é uma solução tecnológica desenvolvida pelo IBICT e repassada gratuitamente às instituições de ensino e pesquisa para que possam gerenciar suas teses e dissertações.						
					</span>
				</li>
			</ol>
		</p>	
	</div>
</div>

<script type="text/javascript">
	function showDesc(id){
		/*$("li > span").each(function(indice,element){
			if($(element).css("display") != 'none' ){
				$(element).hide(1000)
			}
		})*/
		var field = "." + id.id;
		$(field).show(1000);

		$('#' + id.id +'> span').toggleClass('glyphicon-minus-sign iconGreen iconRed').delay(2000)
		$('#' + id.id +'> span:nth-child(2)').toggleClasscss('disable active')

	}
</script>