<div class="row" id="history">
	<div class="col-sm-12">
		<h2 class="titleText">Histórico</h2>
		<h4><span class="subTitText"> CONHEÇA A BIBLIOTECA DIGITAL BRASILEIRA DE TESES E DISSERTAÇÕES (BDTD)</span></h4>
		<div class="text">
			A Biblioteca Digital Brasileira de Teses e Dissertações (BDTD) foi concebida e é mantida pelo Instituto Brasileiro de Informação em Ciência e Tecnologia (IBICT) no âmbito de seu Programa de Acesso Aberto à Informação Científica. A sua criação contou com o apoio da Financiadora de Estudos e Pesquisas (FINEP). Seu lançamento oficial data do final do ano de 2002.
			<br/>
			Para definição do projeto da BDTD foi criado um comitê técnico-consultivo (CTC), instalado no primeiro semestre de 2002, constituído por representantes do IBICT, do Conselho Nacional de Desenvolvimento Científico e Tecnológico (CNPq), Ministério da Educação (MEC) - representado pela Coordenação de Aperfeiçoamento de Pessoal de Nível Superior (CAPES) e pela Secretaria de Educação Superior (SESu)- , da FINEP e de três universidades que participaram de um grupo de trabalho criado e do projeto-piloto (Universidade de São Paulo (USP), Pontifícia Universidade Católica do Rio de Janeiro (PUC-RIO) e a Universidade Federal de Santa Catarina (UFSC)). Coube ao grupo de trabalho o desenvolvimento d o Padrão Brasileiro de Metadados para Teses e Dissertações (MTD-BR), que foi, posteriormente, aprovado pelo CTC. 
			<br/>
			A iniciativa de criação de uma base nacional de teses e dissertações, inicialmente denominada Biblioteca Digital de Teses e Dissertações (BDTD) e, atualmente, denominada Biblioteca Digital Brasileira de Teses e Dissertações (BDTD), teve, então, as seguintes linhas principais de atuação:
			<ul>
				<li>
					Estudar experiências existentes no Brasil e no exterior de desenvolvimento de bibliotecas digitais de teses e dissertações;
				</li>
				<li>
					Desenvolver, em cooperação com membros da comunidade, um modelo para o sistema;
				</li>
				<li>
					Desenvolver, em cooperação com membros da comunidade, um modelo para o sistema;
				</li>
				<li>
					Absorver e adaptar as tecnologias a serem utilizadas na implementação do modelo;
				</li>
				<li>
					Desenvolver um sistema de publicação eletrônica de teses e dissertações para atender àquelas instituições de ensino e pesquisa que não possuíam sistemas automatizados para implantar suas bibliotecas digitais (sistema TEDE);
				</li>
				<li>
					Difundir os padrões e tecnologias adotadas e dar assistência técnica aos potenciais parceiros na implantação das mesmas.
				</li>
			</ul>
			Ao longo dos anos após a sua criação, a BDTD passou por diferentes processos de atualização, desde seu sistema em si como do padrão de metadados utilizado:
			<ul>
				<li>
					2003: aprovação pelo CTC o projeto de reestruturação do sistema da BDTD;
				</li>
				<li>
					2006: lançamento do novo portal da BDTD;
				</li>
				<li>
					2012: início da revisão do Padrão Brasileiro de Metadados para Descrição de Teses e Dissertações (BDTD) e constituição do grupo de trabalho coordenado pelo IBICT, que contou com a participação de 16 instituições brasileiras de ensino e pesquisa participantes da, hoje chamada, Rede BDTD;
				</li>
				<li>
					2012/2013: Início da atualização tecnológica da BDTD (Portal de busca e coletador) e atualização do Sistema de Publicação Eletrônica de Teses e Dissertações (TEDE)
				</li>
				<li>
					2014: Lançamento do novo Padrão de Metadados da BDTD; do novo Sistema da BDTD (Portal e coletador) e; do novo TEDE;
				</li>
				<li>
					2016/2017: Atualização e apresentação do novo Portal da BDTD e coletador de metadados.
				</li>
			</ul>
			Assim, hoje, a BDTD se consolida como uma das maiores iniciativas, do mundo, para a disseminação e visibilidade de teses e dissertações. 
		</div>	
	</div>
</div>