<div class="row" id="work">
	<div class="col-sm-12">
		<h2 class="titleText">Como funciona?</h2>
		<h4><span class="subTitText"> INTEROPERABILIDADE PARA A COOPERAÇÃO!</span></h4>
		<div class="text">
			A Biblioteca Digital Brasileira de Teses e Dissertações (BDTD) foi construída com base nos preceitos da Iniciativa de Arquivos Abertos (OAI), adotando assim, um modelo baseado em padrões de interoperabilidade.

			A interoperabilidade é uma característica de determinados padrões tecnológicos que possibilitam aos computadores intercambiarem informações/dados com outros computadores. É uma forma de comunicação entre sistemas.  A BDTD é uma rede distribuída de sistemas de informação que gerenciam teses e dissertações, com texto completo, com a existência de dois atores principais:
			<ul>
				<li>
					Provedor de dados (data providers) - administra o depósito e publicação, expondo os metadados para a coleta automática (harvesting);
				</li>
				<li>
					Provedor de serviços (service providers) - fornece serviços de informação com base nos metadados coletados junto aos provedores de dados.
				</li>
			</ul>
			As instituições de ensino e pesquisa atuam como provedoras de dados e o IBICT opera como agregador (aquele que reúne): coleta os metadados das teses e dissertações dos provedores (instituições), fornece serviços de informação sobre esses metadados e os expõem para coleta para outros provedores de serviços.
		</div>	
	</div>
</div>