    
<div class="row" id="patterns">
	<div class="col-sm-12">
		<h1><strong>Fontes Coletadas</strong></h1>
 	
		<h3>
			<strong><a class="external-link" href="http://wiki.ibict.br/index.php/Bibliotecas_Digitais_de_Teses_e_Disserta%C3%A7%C3%B5es" target="_blank">Bibliotecas Digitais de Teses e Dissertações</a></strong>	
		</h3>
		<h3>
			<strong><a class="external-link" href="http://www.rcaap.pt/" target="_blank">Repositório Científico de Acesso Aberto de Portugal - RCAAP</a></strong>
		</h3>	
		          
		<iframe src="https://www.google.com/maps/d/embed?mid=z0zroFicy1lI.kv0dg-Nu3CQ8" width="640" height="480"></iframe>		

	</div>
</div>