<div class="row" id="tede">
	<div class="col-sm-12">
		<h2 class="titleText">TEDE</h2>
		<h4><span class="subTitText"> SISTEMA DE PUBLICAÇÃO ELETRÔNICA DE TESES E DISSERTAÇÕES (TEDE)</span></h4>
		<p class="text">
			O Sistema de Publicação Eletrônica de Teses e Dissertações (TEDE) é um software desenvolvido pelo IBICT e distribuído gratuitamente para as instituições que desejam criar suas bibliotecas digitais de teses e dissertações e utilizá-lo para o seu gerenciamento. 
			<br/>

			A primeira versão do sistema foi lançada em 2002, quando do surgimento da BDTD. A mais recente atualização do TEDE foi lançada em 2014 e que passou a ser chamado, desde então, de TEDE 2. A nova versão é uma customização do software livre DSpace, a mesma solução utilizada para a criação de Repositórios Institucionais de Publicações Científicas em Acesso Aberto. 
			<br/>

			O TEDE2 já está configurado de acordo com o Novo Padrão de Metadados da BDTD, sendo totalmente interoperável com outros sistemas de informação. É possível, ainda, fazer customizações na interface e definições do fluxo de trabalho dentro do sistema. 
			<br/>
			As instituições que ainda utilizam o antigo TEDE podem migrar diretamente as suas teses e dissertações para o TEDE2. Para isso, o IBICT desenvolveu também uma ferramenta que possibilita a migração das informações, sem perda de dados e sem que seja necessário fazer trabalho duplicado. 
			<br/>
			Tenha acesso ao manual para uso do TEDE 2:
			<br/><br/>
			<a href="#" target="_blank">
				<span class="glyphicon glyphicon-download fa-2x"> </span> Manual de usuário do TEDE 2
			</a>
			<br/><br/>
			Acesse também as orientações para instalação e customização do TEDE 2: <br/><br/>
			<a href="#" target="_blank">
				<span class="glyphicon glyphicon-link "> </span> TEDE / TEDE 2
			</a><br/>
			<a href="#" target="_blank">
				<span class="glyphicon glyphicon-link "> </span> Instalação, migração e configuração do TEDE 2
			</a><br/>
			<a href="#" target="_blank">
				<span class="glyphicon glyphicon-link "> </span> Matriz de novas funcionalidades implementadas na customização DSpace/TEDE 2
			</a><br/>
			<a href="#" target="_blank">
				<span class="glyphicon glyphicon-link "> </span> Manual de usuário do TEDE 2
			</a><br/>
			<a href="#" target="_blank">
				<span class="glyphicon glyphicon-link "> </span> Configurações básicas / avançadas
			</a><br/>
			<a href="#" target="_blank">
				<span class="glyphicon glyphicon-link "> </span> Problema / solução (Troubleshooting) - TEDE 2
			</a><br/>
		</p>	
	</div>
</div>