<div class="main-footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <section class="block block-block clearfix">
          <img class="image-responsive" src="https://www.argentina.gob.ar/profiles/argentinagobar/themes/argentinagobar/argentinagobar_theme/logo.svg" alt="Argentina.gob.ar - Presidencia de la Nación">          <p class="text-muted small">Los contenidos de Argentina.gob.ar están licenciados bajo <a href="https://creativecommons.org/licenses/by/2.5/ar/" target="_blank">Creative Commons Reconocimiento 2.5 Argentina License</a></p>
          <a class="active" href="/sugerencias-b?url_refence=node/2348">          <p class="btn btn-primary m-t-1">¿Querés hacernos una sugerencia?</p>
          </a>        </section>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="region region-footer2">
          <section id="block-menu-menu-footer-2" class="block block-menu clearfix">
            <ul class="menu nav">
              <li class="first leaf"><a href="https://www.argentina.gob.ar/servicios">Trámites y servicios</a></li>
              <li class="leaf"><a href="https://www.argentina.gob.ar/organismos">Organismos del Estado</a></li>
              <li class="leaf"><a href="https://www.argentina.gob.ar/pais">Nuestro país</a></li>
              <li class="last leaf"><a href="http://mapadelestado.modernizacion.gob.ar/">Mapa del Estado</a></li>
            </ul>
          </section>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="region region-footer3">
          <section id="block-menu-menu-footer-3" class="block block-menu clearfix">
            <ul class="menu nav">
              <li class="first leaf"><a href="https://www.argentina.gob.ar/acerca">Acerca de este sitio</a></li>
              <li class="leaf"><a href="https://www.argentina.gob.ar/terminos-y-condiciones">Términos y condiciones</a></li>
              <li class="last leaf"><a href="https://www.argentina.gob.ar/servicios">Ayuda</a></li>
            </ul>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>