<nav id="w0" class="navbar navbar-top navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#w0-collapse"><span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="http://www.argentina.gob.ar/" target="_blank">
        <img src="https://www.argentina.gob.ar/profiles/argentinagobar/themes/argentinagobar/argentinagobar_theme/logo.svg" width="274" height="50" alt="Inico">
        <h1 class="sr-only">Argentina.gob.ar <small>Presidencia de la Nación</small></h1>
      </a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <? if (!isset($this->layout()->renderingError)): ?>
      <ul role="navigation" class="nav navbar-nav navbar-right">
        <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
        <li class="language dropdown">
          <form method="post" name="langForm" id="langForm">
            <input type="hidden" name="mylang"/>
          </form>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?= $this->transEsc("Language") ?> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
            <li<?= $this->layout()->userLang == $langCode ? ' class="active"' : '' ?>><a href="#" onClick="document.langForm.mylang.value = '<?= $langCode ?>';
                document.langForm.submit()"><?= $this->displayLanguageOption($langName) ?></a></li>
            <? endforeach; ?>
          </ul>
        </li>
        <? endif; ?>
      </ul>
      <? endif; ?>
    </div>
  </div>
</nav>
<? if ($this->layout()->searchbox !== false): ?>
<section id="jumbotronResults" class="jumbotron" style="background-image:url('/vufind/themes/snrd/images/2.jpg');">
  <div class="jumbotron_bar">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ol class="breadcrumb pull-left"><li><a href="https://www.argentina.gob.ar" target="_blank">Inicio</a></li>
            <li>
              <a href="https://www.argentina.gob.ar/ciencia">Ministerio de Ciencia, Tecnología e Innovación Productiva</a>
            </li>
            <li>
              <a href="https://www.argentina.gob.ar/ciencia">Biblioteca Electrónica</a>
            </li>
            <li>SNRD</li>
            <li class="active"><?= $this->transEsc("Search") ?></li>
          </ol>
        </div>
      </div>
    </div>
  </div>
  <div class="jumbotron_body">
    <div class="row">
      <div class="col-xs-12 text-center">
        <h3>Sistema Nacional de Repositorios Digitales</h3>
      </div>
    </div>
  </div>
  <div class="overlay"></div>
</section>
<div class="search container navbar">
  <nav class="nav searchbox hidden-print">
    <?= $this->layout()->searchbox ?>
  </nav>
</div>
<? endif; ?>