<div class="">
	<div class="col-sm-3">
	  <a target="_blank" href="http://www.finep.gov.br/">
	  	<img style="padding-top: 1.5em;" alt="Finep" src="<?=$this->imageLink('Finep.png') ?>">
	  </a>
	</div>
    <div class="col-sm-3">
    	<a target="_blank" href="http://www.rcaap.pt/"><img alt="rcaap" src="<?=$this->imageLink('rcaap.png') ?>"></a>	
	</div>
	<div class="col-sm-3">
		<a target="_blank" href="http://lareferencia.info">
			<img style="padding-top: 1.5em; width: 85%;" alt="laRef" src="<?=$this->imageLink('laref.png') ?>">
		</a>
	</div>
	<div class="col-sm-3">
		<a target="_blank" href="http://www.ibict.br">
			<img style="padding-top: 0.51em;float: right;width: 80%;" class="imagem" alt="Ibict" src="<?=$this->imageLink('IBICTBranco.png') ?>">
		</a>  
	</div>
</div>