  <!--div class="col-sm-4">
    <p><strong><?=$this->transEsc('Link Institucional')?></strong></p>
    <ul>
      <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
      <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
      <li><a href="<?=$this->url('channels-home')?>"><?=$this->transEsc('channel_explore')?></a></li>
      <li><a href="<?=$this->url('search-reserves')?>"><?=$this->transEsc('Course Reserves')?></a></li>
      <li><a href="<?=$this->url('search-newitem')?>"><?=$this->transEsc('New Items')?></a></li>
    </ul>
  </div>
  <div class="col-sm-4">
    <p><strong><?=$this->transEsc('Contato')?></strong></p>
    <ul>
      <li><a href="<?=$this->url('help-home')?>?topic=search&amp;_=<?=time() ?>" data-lightbox class="help-link"><?=$this->transEsc('Search Tips')?></a></li>
      <li><a href="<?=$this->url('content-page', ['page' => 'asklibrary']) ?>"><?=$this->transEsc('Ask a Librarian')?></a></li>
      <li><a href="<?=$this->url('content-page', ['page' => 'faq']) ?>"><?=$this->transEsc('FAQs')?></a></li>
    </ul>
  </div-->
<div class = "footer" style="background-color: #94ab62;/*border-top: 1px solid; box-shadow: 0px 0px 1px*/">
  <div class="row" style="width: 100%; /*background-color: #94ab62;*/">
    <div class="col-sm-3 col-xs-3">
      <a target="_blank" href="http://www.finep.gov.br/">
        <img style="" alt="Finep" src="<?=$this->imageLink('Finep.png') ?>">
      </a>
    </div>
      <div class="col-sm-3 col-xs-3">
        <a target="_blank" href="http://www.rcaap.pt/"><img alt="rcaap" src="<?=$this->imageLink('rcaap.png') ?>"></a>  
    </div>
    <div class="col-sm-3 col-xs-3">
      <a target="_blank" href="http://lareferencia.info">
        <img style="" alt="laRef" src="<?=$this->imageLink('laref.png') ?>">
      </a>
    </div>
    <div class="col-sm-3 col-xs-3">
      <a target="_blank" href="http://www.ibict.br">
        <img style="float: right" class="imagem" alt="Ibict" src="<?=$this->imageLink('logo_ibict.png') ?>">
      </a>  
    </div>
  </div>
</div>