
<? $account = $this->auth()->getManager(); ?>
<div id="barra-brasil">
  <div id="wrapper-barra-brasil">
    <div class="brasil-flag">
      <a href="http://brasil.gov.br" class="link-barra">Brasil</a>
    </div>
    <span class="acesso-info"><a href="http://www.servicos.gov.br/?pk_campaign=barrabrasil" class="link-barra" id="barra-brasil-orgao">Serviços</a></span>
    <nav>
      <ul class="list">
        <li>
          <a href="#" id="menu-icon"></a>
        </li>
        <li class="list-item first">
          <a href="http://brasil.gov.br/barra#participe" class="link-barra">Participe</a>
        </li>
        <li class="list-item">
          <a href="http://brasil.gov.br/barra#acesso-informacao" class="link-barra">Acesso à informação</a>
        </li>
        <li class="list-item">
          <a href="http://www.planalto.gov.br/legislacao" class="link-barra">Legislação</a>
        </li>
        <li class="list-item last last-item">
          <a href="http://brasil.gov.br/barra#orgaos-atuacao-canais" class="link-barra">Canais</a>
        </li>
      </ul>
    </nav>
    <a class="logo-vlibras" href="http://www.vlibras.gov.br/" aria-label="Acessível em Libras"></a>
  </div>
</div>

<div class="banner navbar ">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
      <span class="sr-only">Toggle navigation</span>
      <i class="fa fa-bars" aria-hidden="true"></i>
    </button>    
  </div>

  <? if (!isset($this->layout()->renderingError)): ?>
    <a role="logo" class="navbar-left" style="margin: 15px 0 0 15px" href="<?=$this->url('home')?>">
        <img alt="OASISBR" src="<?=$this->imageLink('logoOasis.png') ?>"  >
    </a>
    <div class="collapse navbar-collapse" id="header-collapse" style="margin: 0 0 0 10em">        
      <nav class="navbar navbar-light">
        <ul class="nav navbar-nav" >
          <li class="active">
              <a  href="<?=$this->url('home')?>" > Início </a>
          </li> 
          <li class="">
              <a class="external-link" href="<?=$this->url('institutions', []) ?>" > Fontes Coletadas </a>
          </li>
          <li class="">
              <a class="external-link" href="<?=$this->url('content-page', ['page' => 'statics']) ?>" > Estatísticas </a>
          </li>
          <li class="dropdown">
              <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                Sobre <b class="caret"></b>    
              </a>
              <ul class="dropdown-menu">
                <li><a href="<?=$this->url('content-page', ['page' => 'howWork']) ?>">Como fazemos? </a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'netWorks']) ?>">Quem participa? </a></li>            
              </ul>
          </li>      
        </ul>
        <ul role="navigation" class="nav navbar-nav navbar-right flip">
          <? if ($this->feedback()->tabEnabled()): ?>
            <li>
              <a id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope" aria-hidden="true"></i> <?=$this->transEsc("Feedback")?></a>
            </li>
          <? endif; ?>
          <? $cart = $this->cart(); if ($cart->isActive()): ?>
            <li id="cartSummary">
              <a id="cartItems" data-lightbox title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
                <i class="fa fa-suitcase" aria-hidden="true"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?>
                <span class="full<?=!$cart->isFull() ? ' hidden' : '' ?>">(<?=$this->transEsc('bookbag_full') ?>)</span>
              </a>
            </li>
          <? endif; ?>
          <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
            <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
              <a href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>"><i class="fa fa-home" aria-hidden="true"></i> <?=$this->transEsc("Your Account")?></a>
            </li>
            <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
              <a href="<?=$this->url('myresearch-logout')?>" class="logout"><i class="fa fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?></a>
            </li>
            <li id="loginOptions"<? if($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
              <? if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                <a href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Institutional Login")?></a>
              <? else: ?>
                <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Login")?></a>
              <? endif; ?>
            </li>
          <? endif; ?>

          <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
            <li class="theme dropdown">
              <form method="post" name="themeForm" id="themeForm">
                <input type="hidden" name="ui"/>
              </form>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <? foreach ($this->layout()->themeOptions as $current): ?>
                  <li<?=$current['selected'] ? ' class="active"' : ''?>><a href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
                <? endforeach; ?>
              </ul>
            </li>
          <? endif; ?>

          <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
            <li class="language dropdown">
              <form method="post" name="langForm" id="langForm">
                <input type="hidden" name="mylang"/>
              </form>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                  <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
                <? endforeach; ?>
              </ul>
            </li>
          <? endif; ?>
        </ul>
      </nav>
    </div>
  <? endif; ?>
</div>

<img alt="barra" src="<?=$this->imageLink('barraAzul.jpg') ?>" style="width:100%;height:8px;margin-top: -7em;">
 


<div id="searchNavBar" class="search1 container navbar">
  <nav class="nav searchbox hidden-print">
    <?=$this->layout()->searchbox ?>
  </nav>
</div>

<script type="text/javascript">
  $('ul.nav li.dropdown').hover(function() {
      $(this).find('.dropdown-menu').stop(true, true).delay(20).fadeIn(500);
    }, 
    function() {
      $(this).find('.dropdown-menu').stop(true, true).delay(20).fadeOut(500);
    }
  );
</script>