<? $this->headTitle($this->translate('Institutions')); ?>

<!--script src="themes/oasis/js/jquery.tabletoCSV.js"></script-->

<script>
$.ajax( {
  type:'Get',
  url:'http://oai.agregador.ibict.br/backend/public/listNetworks',//'http://192.168.0.118:8090/backend/public/listNetworks',
  success:function(data) {
    $.ajax( {
      dataType: 'json',
      type:'Get',
      url:'/vufind/api/v1/search?facet[]=network_acronym_str&sort=relevance&limit=0',
      success:function(dataApi) {
        var acrony      = []
        var countAcrony = []
        var newData     = []

        $.map(dataApi.facets['network_acronym_str'], function(x){
          acrony.push(x.value)
          countAcrony.push(x.count)          
        })
        
        $.each(data,function(index, value){
          if(acrony.includes(value.acronym) ) {            
            value.validSize = countAcrony[acrony.indexOf(value.acronym)];
            newData.push(value);
          }          
        })
        dataTable(newData);
      },
      error: function(x,y,z){
        alert('Erro ao carregar a lista de instituições. Por favor, contate o suporte!!\n Erro : ' + x + y + z)
      },
      complete: function(){
        $("#loading").fadeOut('fast');
      }
    });
  }
});

function dataTable(data){
      $('#inst_table').DataTable( {
        //"iDisplayLength": 50,
        language:{
          "lengthMenu": 'Visualizar '+ 
                        '<select>'+
                          '<option value="10">10</option>'+
                          '<option value="50">50</option>'+
                          '<option value="40">100</option>'+
                          '<option value="-1">Todos</option>'+
                        '</select> registros',
          "search": "Consultar"
        },
        data: data,
        columns: [
            { title: "Nome", data: "name",
            render: function(data, type, row){
                      return  row["url"] == null || row["url"] == ''? data :'<a href="' + row["url"] + '" target = "_blank">' +  data + '</a>';
                    }
            },
            { title: "Institução", data: "institution" },
            { title: "Tipo", data: "type" },
            //{ title: "URL", data: "url" },{ title: "Email", data: "email" },//{ title: "Size", data: "validSize" },
            { title: "Qtd", data: "validSize",
              render: function(data,type,row) {
                return " <a href='/vufind/Search/Results?type=AllFields&filter[]=institution%3A\"" + row["institution"] + "\" '>" + row["validSize"] + "</a>"  ;
              }
            },
        ]
    } );
}
</script>


<div class="col-sm-12">
  <h2>Instituições participantes</h2>
  <h4><span class="subTitText"> CONHEÇA AS INSTITUIÇÕES PARTICIPANTES DO PORTAL BRASILEIRO DE PUBLICAÇÕES CIENTÍFICAS EM ACESSO ABERTO (OASISBR)</span></h4>
  <p>
    Aguarde o carregamento completo da tabela com as instituições participantes do oasisbr.
  </p>
  <div id="loading" style="margin-bottom: .5em;text-align: center;">
    <img src="http://i.stack.imgur.com/Z4BUx.gif" alt="Carregando..." title="Carregando..." style="width: 3%">
  </div>
  <div style="margin-bottom: .5em;">
    <button id="export" data-export="export" class="btn btn-warning"><?=$this->transEsc('Export to CSV')?></button>
  </div>
  <table id="inst_table" class="display"></table>
</div>

<script>
  $("#export").click(function(){
    $("#inst_table").tableToCSV();
  });
</script>
