<footer role="contentinfo" class="hidden-print">
  <section class="t3-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-12 copyright ">
          <div class="row">
            <div class="col-md-12 col-sm-12">
              <div class="custom">
                <p style="text-align: center;"><img src="<?= $this->imageLink('logofooter.png') ?>" alt="LA Referencia"></p>
                <p style="text-align: center;"><span id="cloake1737c8de59b337430caa82f24971593"><a href="mailto:repositoriosla@gmail.com">repositoriosla@gmail.com</a></span><script type="text/javascript">
                  document.getElementById('cloake1737c8de59b337430caa82f24971593').innerHTML = '';
                  var prefix = '&#109;a' + 'i&#108;' + '&#116;o';
                  var path = 'hr' + 'ef' + '=';
                  var addye1737c8de59b337430caa82f24971593 = 'r&#101;p&#111;s&#105;t&#111;r&#105;&#111;sl&#97;' + '&#64;';
                  addye1737c8de59b337430caa82f24971593 = addye1737c8de59b337430caa82f24971593 + 'gm&#97;&#105;l' + '&#46;' + 'c&#111;m';
                  var addy_texte1737c8de59b337430caa82f24971593 = 'r&#101;p&#111;s&#105;t&#111;r&#105;&#111;sl&#97;' + '&#64;' + 'gm&#97;&#105;l' + '&#46;' + 'c&#111;m';
                  document.getElementById('cloake1737c8de59b337430caa82f24971593').innerHTML += '<a ' + path + '\'' + prefix + ':' + addye1737c8de59b337430caa82f24971593 + '\'>' + addy_texte1737c8de59b337430caa82f24971593 + '<\/a>';
                  </script> | <a href="/joomla/es/preguntas-frecuentes" target="_blank">Preguntas Frecuentes</a><br><a href="http://repositoriosdigitales.mincyt.gob.ar:8380/dnet-web-generic/" target="_blank">Argentina</a>&nbsp;| <a href="http://oasisbr.ibict.br/vufind/" target="_blank">Brasil</a>&nbsp;| <a href="http://www.sic.informacioncientifica.cl/" target="_blank">Chile</a>&nbsp;| <a href="http://190.242.114.6:8080/web/guest/inicio" target="_blank">Colombia</a>&nbsp;| <a href="http://kimuk.conare.ac.cr/" target="_blank">Costa Rica</a>&nbsp;| <a href="http://rraae.org.ec/" target="_blank">Ecuador</a>&nbsp;| <a href="http://www.redicces.org.sv/jspui/" target="_blank">El Salvador</a>&nbsp;| <a href="http://www.remeri.org.mx/portal/index.html" target="_blank">México</a>&nbsp;|&nbsp;<a href="http://alicia.concytec.gob.pe/vufind/" target="_blank">Perú</a></p>
                <p style="text-align: center;"><a href="http://creativecommons.org/licenses/by/4.0/"><img src="http://i.creativecommons.org/l/by/3.0/88x31.png" alt="by" style="font-size: 12.16px;"></a>&nbsp; A menos que se indique lo contrario, todos los materiales&nbsp;producidos por LA Referencia&nbsp;tienen una<a href="http://creativecommons.org/licenses/by/4.0/"> licencia CC 4.0 Internacional&nbsp;</a></p>
                <p style="text-align: center;"><a href="http://creativecommons.org/licenses/by/4.0/"></a></p></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</footer>