<div class="col-xs-12" id="bdtd15">
	<div class="col-xs-12">
		<h2 class="titleText">BDTD 15 anos</h2>
		<h4><span class="subTitText"> PARABÉNS À BIBLIOTECA DIGITAL BRASILEIRA DE TESES E DISSERTAÇÕES (BDTD)! 15 ANOS!</span></h4>
		<p class="text">
			No ano de 2017, a Biblioteca Digital Brasileira de Teses e Dissertações (BDTD) completa 15 anos!			
			<br/>
			Ao longo desses anos, a BDTD tem se consolidado como uma importante base de informação para dar visibilidade aos resultados de pesquisas oriundos dos programas de pós-graduação das instituições brasileiras de ensino e pesquisa. Também, a comunidade acadêmica tem reconhecido a grande potencialidade de informações que podem ser extraídas da BDTD para a geração de diversos estudos. 

			<br/>
			Além da visibilidade proporcionada às teses e dissertações brasileiras, a BDTD muito contribui para a visibilidade da ciência produzida na região da América Latina e da ciência em Língua Portuguesa. 
			<br/><br/>
			Vida longa à BDTD!
		</p>	
	</div>
</div>