<div class="col-xs-12" id="work">
	<div class="col-xs-12">
		<h2 class="titleText">Como funciona?</h2>
		<h4><span class="subTitText"> INTEROPERABILIDADE E COOPERAÇÃO!</span></h4>
		<div class="text">
			A Biblioteca Digital Brasileira de Teses e Dissertações (BDTD) segue os preceitos da Iniciativa de Arquivos Abertos (OAI), adotando assim, o modelo baseado em padrões de interoperabilidade.
			<br><br>
			A BDTD é uma rede distribuída de sistemas de informação que gerenciam teses e dissertações, com texto completo, com a existência de dois atores principais:
			<ul>
				<li>
					Provedor de dados (data providers) - administra o depósito e publicação, expondo os metadados para a coleta automática (harvesting);
				</li>
				<li>
					Provedor de serviços (service providers) - fornece serviços de informação com base nos metadados coletados junto aos provedores de dados.
				</li>
			</ul>
			Assim, as instituições de ensino e pesquisa atuam como provedoras de dados e o IBICT opera como agregador: coleta os metadados das teses e dissertações dos provedores (instituições), fornece serviços de informação sobre esses metadados e os expõem para coleta para outros provedores de serviços.
		</div>	
	</div>
</div>