<div class="col-xs-12" id="whatis">
	<div class="col-xs-12">
		<h2 class="titleText">Novidades!</h2>
		<h4><span class="subTitText"> Estamos trabalhando para mehorar cada vez mais nossos serviços. </span></h4>
		<span class="text">
			Algumas mudanças que acontecerão em breve:
		</span>
			
		<ol style="line-height: 2.5em;">
			<li>
				Opção para visualizar todos os detalhes de todas as teses/dissertações consultadas;
			</li>
			<li>
				Exportação CSV:
				<ol type="i">
					<li>
						Os campos orientador e co-orientador estarão em campos separados;
					</li>
					<li>
						ID Lattes será padronizado com 16 digítos;
					</li>
					<li>
						Áreas e sub-áreas estarão em campos separados;
					</li>
					<li>
						Padronização do enconding.
					</li>
				</ol>						
			</li>
			<li>
				Busca avançada "Todos Campos Textuais". Esse tipo de busca irá realizar a consulta em todos os campos textuais com exceção nome autor, orientador, co-orientador e membros da banca;
			</li>
			<li>
				Inserção da UF (Unidade Federativa) das instituições;
			</li>
			<li>
				Padronizar os programas de pós-graduação de acordo com a lista de programas do CNPq;
			</li>
			<li>
				Integrar bibliotecas:
				<ol type="i">
					<li> jsLDA; </li>
					<li> jsPivot; </li>
					<li> Carrot 2; </li>
				</ol>
			</li>
			<li>
				Novos formatos de exportação:
				<ol type="i">
					<li> XML; </li>
					<li> Iramuteq; </li>
				</ol>
			</li>
		</ol>
		<br/>
		A cada nova atualização das mudanças propostas acima, nós iremos atualizar essa lista com o que já foi implementado.
		<br/><br/>
		<span style="font-weight: bold;">  Conheça! Participe! Divulgue! </span>
	</div>
</div>