<div class="col-xs-12" id="participe">
	<div class="col-xs-12">
		<h2 class="titleText">Como participar?</h2>
		<h4><span class="subTitText"> SAIBA COMO PARTICIPAR DA BIBLIOTECA DIGITAL BRASILEIRA DE TESES E DISSERTAÇÕES (BDTD)</span></h4>
		<p class="text">
			Para participar da Biblioteca Digital Brasileira de Teses e Dissertações (BDTD) é necessário que a instituição possua curso(s) de pós-graduação stricto sensu. Para o processo de integração da instituição à BDTD é necessário o encaminhamento de uma comunicação formal manifestando o interesse em fazer parte da BDTD. 
			<br><br>
			Após recebimento do documento, a Equipe da BDTD entrará em contato com o responsável indicado para o seguimento do processo de integração à BDTD.
			
		</p>
	</div>
</div>