    
<div class="col-xs-12" id="patterns">
	<div class="col-xs-12">
		<h2 class="titleText">Padrões e diretrizes</h2>
		<h4><span class="subTitText">CONHEÇA OS PADRÕES E DIRETRIZES DA BDTD</span></h4>

		<p class="text">
			O uso dos padrões e diretrizes da Biblioteca Digital Brasileira de Teses e Dissertações (BDTD) é fundamental para que se garanta a interoperabilidade entre os sistemas de informação. Desde a sua concepção, a BDTD utiliza o Padrão Brasileiro de Metadados para Descrição de Teses e Dissertações (MTD-BR). O Padrão brasileiro foi desenvolvido também analisando outros padrões internacionais para a descrição dessa tipologia documental, como o Electronic Thesis and Dissertations Metadata Standard (ETD-MS). 
			<br>
			Ao longo dos anos, o Padrão brasileiro também foi atualizado, acompanhando as mudanças dos padrões internacionais, os novos sistemas e formatos. Assim, hoje, a BDTD utiliza a terceira versão do Padrão, o MTD3-BR. 

			<br><br>

			<a href="#" target="_blank">
				<span class="fa fa-download fa-2x"></span> Padrão Brasileiro de Metadados para Descrição de Teses e Dissertações (MTD-BR) v. 1
			</a>
			<br>
			<a href="#" target="_blank">
				<span class="fa fa-download fa-2x"></span> Padrão Brasileiro de Metadados para Descrição de Teses e Dissertações (MTD2-BR) v. 2
			</a>
			<br>
			<a href="#" target="_blank">
				<span class="fa fa-download fa-2x"></span> Padrão Brasileiro de Metadados para Descrição de Teses e Dissertações (MTD3-BR) v. 3
			</a>

		</p>		
	</div>
</div>