<div class="col-xs-12" id="tecnology">
	<div class="col-xs-12">
		<h2 class="titleText">Tecnologias</h2>
		<h4><span class="subTitText"> SOLUÇÕES LIVRES</span></h4>
		<p class="text">
			A Biblioteca Digital Brasileira de Teses e Dissertações (BDTD) desde a sua criação faz uso de soluções livres em toda a sua estrutura de funcionamento. 
			<br/>
			A BDTD utiliza o software livre VuFind para agregar e disponibilizar as teses e dissertações coletadas dos sistemas de informação gerenciados pelas instituições.
			<br/>
			Recentemente a BDTD passou a adotar o coletador desenvolvido e utilizado pela <strong>Rede de Repositorios de Acceso Abierto a la Ciencia (LA Referencia).</strong>
			<br/>
		</p>	
	</div>
</div>