<div class="col-xs-12" id="whatis">
	<div class="col-xs-12">
		<h2 class="titleText">O que é?</h2>
		<h4><span class="subTitText"> DAR ACESSO AOS TEXTOS COMPLETOS DAS TESES E DISSERTAÇÕES DEFENDIDAS EM TODO O PAÍS SEM QUAISQUER CUSTOS</span></h4>
		<p class="text">
			A Biblioteca Digital Brasileira de Teses e Dissertações (BDTD) integra e dissemina, em um só portal de busca, os textos completos das teses e dissertações defendidas nas instituições brasileiras de ensino e pesquisa. O acesso a essa produção científica é livre de quaisquer custos.
			<br/><br/>
			A BDTD contribui para o aumento de conteúdos de teses e dissertações brasileiras na internet, o que significa a maior visibilidade da produção científica nacional e a difusão de informações de interesse científico e tecnológico para a sociedade em geral.
			<br/>
			Além disso, a BDTD também proporciona maior visibilidade e governança do investimento realizado em programas de pós-graduação. 
			<br/><br/>
			<span style="font-weight: bold;">  Conheça! Participe! Divulgue! </span>
		</p>	
	</div>
</div>