<script>

$.ajax({
        type: 'GET',
        //url: '/vufind/api/v1/search?type=AllFields&facet[]=reponame_str&sort=reponame_str&page=1&limit=0&prettyPrint=false&lng=es',
        url: 'http://biblio-int.mincyt.gob.ar/api/repos',
        beforeSend: function(){
            $('#repos').append('<i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i><span class="sr-only">Cargando listado...</span>');
        },
        success: function(data){

           $.each(data, function(index, value){
                $('#repos').append('<div class="col-xs-12 col-sm-6"><div class="repoCard" id="'+value.id+'"><img src="/vufind/themes/snrd/images/repobanners/'+value.nombre_clave+'.jpg" class="img-responsive" /><div class="main-body"><div class="repoNameContainer"><h1 class="repoName">'+value.name+'</h1></div><!-- <p class="small text-justify">'+value.description+'</p>--></div><div class="footer">&nbsp;</div></div></div>');

                $.ajax({
                    type: 'GET',
                    url: '/vufind/api/v1/search?type=AllFields&filter[]=reponame_str%3A%22'+value.nombre_clave+'%22&facet[]=reponame_str&limit=0&lng=<?=$this->layout()->userLang?>',
                    success: function (data){
                        $('#'+value.id+' .repoNameContainer').after('<h1 class="records">'+addSeparator(data.resultCount)+'<small><?= $this->transEsc('harvested records')?></small></h1><p class="institution">'+value.under.replace('. ','<br>')+'</p>');
                        $('#'+value.id+' .footer').html('<div class="row"><div class="col-sm-6"><a class="browseRepo" href="/vufind/Search/Results?filter%5B%5D=~reponame_str%3A%22'+value.nombre_clave+'%22"><i class="fa fa-search fa-fw"></i> <?= $this->transEsc('Browse') .' '. $this->transEsc('repository') ?></a></div><div class="col-sm-6"><a class="visitRepo" href="http://'+value.url_repo+'" target="_blank"><i class="fa fa-home fa-fw"></i> <?= $this->transEsc('Visit web') ?> </a></div></div>');
                    }
                })

            });
        }
    })
    </script>

<? $this->headTitle($this->translate('Repositories')); ?>
<? $this->layout()->breadcrumbs = '<li class="active"><a href="'.$this->url('home').'">' .  $this->translate('Home') . '</a></li><li class="active">' . $this->translate('Repositories') . '</li> '; ?>
<div class="container main-info">
    <h1 class="page-header"><?=$this->translate('Repositories') ?></h1>
    <div id="repos" class="row"></div>
    <div class="clearfix"></div>
</div>