<?
  // Set page title.
  $this->headTitle($this->translate('oasisbr'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = false;
?>
<div class="row">
  <div class="col-sm-12">    
    <div style="margin-bottom:1.5em;margin-top: -1em;">
      <img style="margin-left: auto;margin-right: auto;display: block;" alt="oasisbr" src="<?=$this->imageLink('oasis-02.png') ?>" width="35%">
      
    </div>    
    <!--p style="font-size: 15px">Conhecimento e reconhecimento para a pesquisa cientícia brasileira.</p-->
  </div>
</div>

<div class="searchHomeContent">
  <?
  $ilsStatusScript = <<<JS
      $(document).ready(function() {
        $.ajax({
            dataType: 'json',
            method: 'GET',
            data: {'offlineModeMsg':'ils_offline_home_message'},
            url: VuFind.path + '/AJAX/JSON?method=getIlsStatus',
            success: function(response) {
                $('.searchHomeContent').append(response.data);
            }
        });
      });
JS;
  ?>
  <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $ilsStatusScript, 'SET'); ?>
  <div class="well well-lg clearfix row" role="search">
    <?=$this->context($this)->renderInContext("search/searchbox.phtml", ['ignoreHiddenFilterMemory' => true])?>
  </div>
  <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, '$("#searchForm_lookfor").focus();', 'SET'); ?>
</div>

<!--
<? if (isset($facetList) && is_array($facetList)): ?>
  <div class="row">
    <? foreach ($facetList as $field => $details): ?>
      <? if (isset($this->hierarchicalFacets) && in_array($field, $this->hierarchicalFacets)): ?>
        <? $this->headScript()->appendFile('vendor/jsTree/jstree.min.js'); ?>
        <? $this->headScript()->appendFile('facets.js'); ?>
        <? $sort = isset($this->hierarchicalFacetSortOptions[$field]) ? $this->hierarchicalFacetSortOptions[$field] : ''; ?>
        <?
        $script = <<<JS
$(document).ready(function() {
  initFacetTree($('#facet_{$this->escapeHtml($field)}'), false);
});
JS;
        ?>
        <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
        <div class="facet <?=$field=='callnumber-first' ? 'col-sm-6' : 'col-sm-3' ?>">
          <h2><?=$this->transEsc('home_browse') . ' ' . $this->transEsc($details['label'])?></h2>
          <div id="facet_<?=$this->escapeHtml($field)?>" class="jstree-facet"
              data-facet="<?=$this->escapeHtml($field)?>"
              data-path="<?=$this->url($basicSearch)?>"
              data-exclude="0"
              data-operator="AND"
              data-exclude-title="<?=$this->transEsc('exclude_facet')?>"
              data-sort="all">
          </div>
        </div>
        <noscript>
      <? endif; ?>
      <? $sortedList = $this->sortFacetList($this->results, $field, $details['list'], $basicSearch); ?>
      <div class="<?=$field=='callnumber-first' ? 'col-sm-6' : 'col-sm-3' ?>">
        <h2><?=$this->transEsc('home_browse') . ' ' . $this->transEsc($details['label'])?></h2>
        <div class="row">
          <ul class="list-unstyled <?=$field == "callnumber-first" ? 'col-sm-6' : 'col-sm-12' ?>">
          <? /* Special case: two columns for LC call numbers... */ ?>
          <? if ($field == "callnumber-first"): ?>
            <? $i = 0; foreach ($sortedList as $url => $value): ?>
              <? if (!empty($value)): ?>
                <li><a href="<?=$url?>"><?=$this->escapeHtml($value)?></a></li>
              <? else: $i--; ?>
              <? endif; ?>
              <? if (++$i == 10): ?>
                </ul><ul class="list-unstyled col-sm-6">
              <? endif; ?>
            <? endforeach; ?>
          <? /* Special case: collections */ ?>
          <? elseif ($field == 'hierarchy_top_title'): ?>
            <? $i = 0; foreach ($sortedList as $url => $value): ?>
              <? if (++$i > 10): ?>
                <li><a href="<?=$this->url('collections-home')?>"><strong><?=$this->transEsc("More options")?>...</strong></a></li>
                <? break; ?>
              <? else: ?>
                <li><a href="<?=$this->url('collections-bytitle')?>?title=<?=urlencode($value)?>"><?=$this->escapeHtml($value)?></a></li>
              <? endif; ?>
            <? endforeach; ?>
          <? else: ?>
            <? $i = 0; foreach ($sortedList as $url => $value): ?>
              <? if (++$i > 10): ?>
                <li><a href="<?=$this->url($advSearch)?>"><strong><?=$this->transEsc("More options")?>...</strong></a></li>
                <? break; ?>
              <? elseif (!empty($value)): ?>
                <li><a href="<?=$url?>"><?=$this->escapeHtml($value)?></a></li>
              <? else: $i--; ?>
              <? endif; ?>
            <? endforeach; ?>
          <? endif; ?>
          </ul>
        </div>
      </div>
      <? if (isset($this->hierarchicalFacets) && in_array($field, $this->hierarchicalFacets)): ?>
        </noscript>
      <? endif; ?>
    <? endforeach; ?>
  </div>
<? endif; ?>
-->

<div class="row numStats" >
  <div class="rowStats row">
    <div class="col-xs-4" style="text-align: center;">
        <span id="revista" class="ntwrk-number">
          <div id="loading" style="margin-bottom: -.5em;text-align: center;">
            <img src="http://i.stack.imgur.com/Z4BUx.gif" alt="Carregando..." title="Carregando..." style="width: 5%">
          </div>
        </span>
        <span class="ntwrk-txt"><br><?=$this->transEsc('Scientific Journals')?></span>
    </div>
    <div class="col-xs-4" style="text-align: center;">              
        <span id="ri" class="ntwrk-number">
          <div id="loading" style="margin-bottom: -.5em;text-align: center;">
            <img src="http://i.stack.imgur.com/Z4BUx.gif" alt="Carregando..." title="Carregando..." style="width: 5%">
          </div>
        </span><br>
        <span class="ntwrk-txt"><?=$this->transEsc('Institutional Repositories')?></span>
      </div>
      <div class="col-xs-4" style="text-align: center;">              
        <span id="bdtd" class="ntwrk-number">
          <div id="loading" style="margin-bottom: -.5em;text-align: center;">
            <img src="http://i.stack.imgur.com/Z4BUx.gif" alt="Carregando..." title="Carregando..." style="width: 5%">
          </div>
        </span><br>
        <span class="ntwrk-txt"><?=$this->transEsc('Thesis and Dissertation Libraries')?></span>
    </div>          
  </div>
</div>

<div class="row" style="padding: 0 0 2em 0;" id="infos">
  <div class="container">
    <div class="col-md-4 md-margin-bottom-40">
      <div class="headline">
          <h2><strong><?=$this->transEsc('Sobre o oasisbr')?></strong></h2>        
      </div> 
      <p style="text-align: justify; margin-bottom: 25px;">
        O Portal brasileiro de publicações científicas em acesso aberto - oasisbr é um mecanismo de busca multidisciplinar que permite o acesso gratuito à produção científica de autores vinculados a universidades e institutos de pesquisa brasileiros. Por meio do oasisbr é possível também realizar buscas em fontes de informação portuguesas.
      </p>       
    </div>
    <div class="col-md-4 md-margin-bottom-40">
      <div class="headline">
          <h2><strong><?=$this->transEsc('Link Institucional')?></strong></h2>        
      </div> 
      <p style="text-align: justify; margin-bottom: 25px;">
        <a href="http://www.ibict.br/informacao-para-ciencia-tecnologia-e-inovacao%20/portal-brasileiro-de-acesso-aberto-a-informacao-cientifica-oasisbr" target="_blank">http://www.ibict.br</a>
      </p>
      <div class="headline">
          <h2><strong><?=$this->transEsc('Contato')?></strong></h2>        
      </div> 
      <address class="md-margin-bottom-40">
        Email: <a href="mailto: oasisbr@ibict.br" class="">
          oasisbr@ibict.br</a><br>
        Telefone: +55 61 3217-6449/6460 <br><br>      
      </address>
    </div>
    <div class="col-md-4 md-margin-bottom-40">
      <div class="headline">
          <h2><strong><?=$this->transEsc('Contato')?></strong></h2>        
      </div> 
      <iframe style="width: 340px; height: 191px; left: 0px; top: 4.375px;" class="embed-responsive-item" src="https://www.youtube.com/embed/BdvsH84uxPQ" frameborder="0" allowfullscreen></iframe>
      <div>
        <a class="" target="_blank" href="https://www.facebook.com/acessoabertobrasil/?fref=ts">
          <img width="10%" src="http://1.bp.blogspot.com/-WSdqH3gMHDk/U-xndvvQYrI/AAAAAAAABwg/9OLHbIjiTF8/s1600/facebook%2Blogo%2Bpng%2Btransparent%2Bbackground.png" alt="oasisbr">
        </a>                
      </div>        
    </div>
  </div>
</div>
<div class="container content" id="partners">  
  <div class="partners">
    <div class="headline">
      <h4><strong>Nossos Parceiros</strong></h4>
    </div>
    <div class="row" style="margin: 0 0 5em 0;">
      <!--div class="viewport col-sm-1 col-xs-3" id="partns-viewport">
        <a target="_blank" href="http://www.lareferencia.info">
          <img class="partner-color" src="<?=$this->imageLink('partners/laref.png') ?>" alt="La-referencia" style="width:100%;">
        </a>
      </div>
      <div class="viewport col-sm-1 col-xs-3" id="partns-viewport">
        <a target="_blank" href="http://www.recaap.org/">
              <img class="partner-color" src="<?=$this->imageLink('partners/rcaap.png') ?>" alt="recaap" style="width:100%;">
            </a>
      </div>
      <div class="viewport col-sm-1 col-xs-3" id="partns-viewport">
        <a target="_blank" href="http://www.lareferencia.info">
          <img class="partner-color" src="<?=$this->imageLink('partners/banner.jpg') ?>" alt="scielo" style="width:100%;">
        </a>
      </div>
      <div class="viewport col-sm-1 col-xs-3" id="partns-viewport">
        <a target="_blank" href="http://www.lareferencia.info">
          <img class="partner-color" src="<?=$this->imageLink('partners/cplp.png') ?>" alt="cplp"  style="width:100%;">
        </a>
      </div>
      <div class="viewport col-sm-1 col-xs-3" id="partns-viewport">
        <a target="_blank" href="http://www.lareferencia.info">
          <img class="partner-color" src="<?=$this->imageLink('partners/coar.png') ?>" alt="coar" style="width:100%;">
        </a>
      </div>
      <div class="viewport col-sm-1 col-xs-3" id="partns-viewport">
        <a target="_blank" href="http://www.lareferencia.info">
          <img class="partner-color" src="<?=$this->imageLink('partners/ndltd.png') ?>" alt="ndltd" style="width:100%;">
        </a>
      </div>
      <div class="viewport col-sm-1 col-xs-3" id="partns-viewport">
        <a target="_blank" href="http://www.lareferencia.info">
          <img class="partner-color" src="<?=$this->imageLink('partners/bdtd.png') ?>" alt="bdtd"  style="width:100%;">
        </a>
      </div-->
      <div class="viewport col-sm-12 col-xs-12" id="partns-viewport" style="text-align: center;">
            <a target="_blank" href="http://www.lareferencia.info">
              <img class="partner-color" src="<?=$this->imageLink('partners/laref.png') ?>" alt="La-referencia" style="width: 13%; margin: 5px">
              </a>
            <a target="_blank" href="http://www.recaap.org/">
              <img class="partner-color" src="<?=$this->imageLink('partners/rcaap.png') ?>" alt="recaap" style="width: 13%;margin: 5px">
            </a>
            <a target="_blank" href="http://www.scielo.org/php/index.php">        
                <img class="partner-color" src="<?=$this->imageLink('partners/banner.jpg') ?>" alt="scielo" style="width: 13%;margin: 5px">
              </a>
            <a target="_blank" href="http://www.cplp.org/">
              <img class="partner-color" src="<?=$this->imageLink('partners/cplp.png') ?>" alt="cplp" style="width: 13%;margin: 5px">
              </a>
            <a target="_blank" href="https://www.coar-repositories.org/">
              <img class="partner-color" src="<?=$this->imageLink('partners/coar.png') ?>" alt="coar" style="width: 13%;margin: 5px">
              </a>
            <a target="_blank" href="http://www.ndltd.org/">
              <img class="partner-color" src="<?=$this->imageLink('partners/ndltd.png') ?>" alt="ndltd" style="width: 13%;margin: 5px">
              </a>
            <a target="_blank" href="http://bdtd.ibict.br">
              <img class="partner-color" src="<?=$this->imageLink('partners/bdtd.png') ?>" alt="bdtd" style="width: 13%;margin: 5px">
            </a>          
        </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  /* 
    /vufind/Search/Results?limit=0&lookfor=%2A%3A%2A&type=AllFields&filter%5B%5D=format%3A%22masterThesis%22
  */
    
$.ajax({
      type: 'Get',
      url: 'http://oai.agregador.ibict.br/backend/public/listNetworks',
      success: function(data){
        $.ajax( {
          dataType: 'json',
          type:'Get',
          url:'/vufind/api/v1/search?facet[]=network_acronym_str&sort=relevance&limit=0',
          success:function(dataApi) {
            var acrony      = []
            var countAcrony = []
            var newData     = []

            $.map(dataApi.facets['network_acronym_str'], function(x){
              acrony.push(x.value)
              countAcrony.push(x.count)          
            })
            
            $.each(data,function(index, value){
              if(acrony.indexOf(value.acronym) != -1 ) {            
                value.validSize = countAcrony[acrony.indexOf(value.acronym)];
                newData.push(value);
              }          
            })

            console.log(newData);
            //listInsti.push(data );
            var dados = newData.map(function(value){
              return {data: value.type}
            })

            var countType = d3.nest()
                .key(function(d){ return d.data } )
                .rollup(function(v){ return v.length } )
                .entries(dados)
           
            $.each(countType, function(index, data ) {
                data.key = data.key.toLowerCase()

                /* If para trocar a KEY do JSON para coincidir com os ID das tags HTML*/
                if(data.key == 'repositório institucional'){
                  data.key = 'ri'
                }else if(data.key == "biblioteca de teses e dissertações"){
                  data.key = 'bdtd'
                }
            
          
                /*ALTERANDO O NÚMERO DE QUANTIDADE DE REPOSITÓRIOS*/
                //$("#" + data.key).html(data.value);
                var format = d3.format(",d");
                var number = data.value;

                d3.select("#" + data.key)
                    .transition()
                    .duration(2500)
                    .on("start", function repeat() {
                      d3.active(this)
                        .tween("text", function() {
                            var that = d3.select(this),
                                i = d3.interpolateNumber(that.text().replace(/,/g, ""), number);
                            return function(t) { that.text(format(i(t))); };
                        })
                        .transition()
                        .delay(1500)
                    });           
                  $("#loading").fadeOut('fast');
            })
          },//FIM DO SUCESS DATA API
          error: function(x,y,z){
            alert('Erro ao carregar a lista de instituições. Por favor, contate o suporte!!\n Erro : ' + x + y + z)
          },
          complete: function(){
            $("#loading").fadeOut('fast');
          }
        });//FIM AJAX DATAAPI
    }//FIM SUCCESS DATA
});// FIM AJAX DATA

</script>
