<?
  // Set page title.
  $this->headTitle($this->translate('BDTD'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = false;
?>

<div class="row">
  <div class="col-sm-12">
    <!--h1 class="page-header" style="color:#0a630a">
    	BDTD - Biblioteca Digital Brasileira de Teses e Dissertações
    </h1>
    <div style="margin-bottom:1.5em;margin-top: -1em;">
    	<img style="margin-left: auto;margin-right: auto;display: block;" alt="BDTD" src="<?=$this->imageLink('logoBdtdMain.png') ?>" width="50%">
    </div>
    <!--p style="font-size: 15px">Conhecimento e reconhecimento para a pesquisa cientícia brasileira.</p-->
  </div>
</div>
<div class="searchHomeContent">
  <?
  		$ilsStatusScript = <<<JS
      		$(document).ready(function() {
        		$.ajax({
            		dataType: 'json',
            		method: 'GET',
            		data: {'offlineModeMsg':'ils_offline_home_message'},
            		url: VuFind.path + '/AJAX/JSON?method=getIlsStatus',
            		success: function(response) {
                		$('.searchHomeContent').append(response.data);
            		}
        		});
      		});
JS;
  	?>
  		<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $ilsStatusScript, 'SET'); ?>
  		<div class="well well-lg clearfix" role="search">
  			<div id="textMain" class="textMain">
				<h1>ACESSO E VISIBILIDADE ÀS TESES E DISSERTAÇÕES BRASILEIRAS</h1>
			</div>

    		<?=$this->context($this)->renderInContext("search/searchbox.phtml", ['ignoreHiddenFilterMemory' => true])?>

  			<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, '$("#searchForm_lookfor").focus();', 'SET'); ?>
		</div>
		<!--style="background-color: #0a630a;padding: 1em;border-radius: 4px;margin-left: auto;margin-right: auto;margin-top: 1em;box-shadow: 0.1em 0.1em 0.2em;"-->
    <script>
      $.ajax( {
        type:'Get',
        url:'/vufind/api/v1/search?lookfor=*%3A*&type=AllFields&facet[]=format&facet[]=institution&limit=0',

        success:function(data) {
          var format = d3.format(",d");
          //$("#docSize" ).html(data.resultCount.toLocaleString('de-DE'));
          d3.select('#docSize')
            .transition()
            .duration(2500)
            .on("start", function repeat() {
              d3.active(this)
                .tween("text", function() {
                    var that = d3.select(this),
                        i = d3.interpolateNumber(that.text().replace(/,/g, ""), data.resultCount);
                    return function(t) { that.text(format(i(t))); };
                })
                .transition()
                .delay(1500)
            });           
          $("#loading").fadeOut('fast');

          //$("#instSize" ).html(data.facets.institution.length);
          d3.select('#instSize')
            .transition()
            .duration(2500)
            .on("start", function repeat() {
              d3.active(this)
                .tween("text", function() {
                    var that = d3.select(this),
                        i = d3.interpolateNumber(that.text().replace(/,/g, ""), data.facets.institution.length);
                    return function(t) { that.text(format(i(t))); };
                })
                .transition()
                .delay(1500)
            });           
          $("#loading").fadeOut('fast');

          $.each(data.facets.format, function( index, facet ) {              
              var number = facet.count;

                d3.select("#" + facet.value)
                    .transition()
                    .duration(2500)
                    .on("start", function repeat() {
                      d3.active(this)
                        .tween("text", function() {
                            var that = d3.select(this),
                                i = d3.interpolateNumber(that.text().replace(/,/g, ""), number);
                            return function(t) { that.text(format(i(t))); };
                        })
                        .transition()
                        .delay(1500)
                    });           
                  $("#loading").fadeOut('fast');

            //$("#" + facet.value ).html(facet.count.toLocaleString('de-DE'));
            //$("#" + facet.value + 'Anchor').html(facet.translated);
            //$("#" + facet.value + 'Anchor').attr("href", "/vufind/Search/Results" + facet.href);
          });
        }
      });
    </script>
    <div class="numStats">      
  		<div class="rowStats row text-center">
        <div class="col-md-3 col-xs-6">
          <span id="instSize" class="ntwrk-number">
            <div id="loading" style="margin-bottom: -.5em;text-align: center;">
              <img src="http://i.stack.imgur.com/Z4BUx.gif" alt="Carregando..." title="Carregando..." style="width: 5%">
            </div>
          </span>
          <span class="ntwrk-txt"><br>
            <a href="<?=$this->url('institutions', []) ?>"><?=$this->transEsc('Institution')?> </a>
          </span>
        </div>
        <div class="col-md-3 col-xs-6">
          <span id="masterThesis" class="ntwrk-number">
            <div id="loading" style="margin-bottom: -.5em;text-align: center;">
              <img src="http://i.stack.imgur.com/Z4BUx.gif" alt="Carregando..." title="Carregando..." style="width: 5%">
            </div>
          </span><br>
          <span class="ntwrk-txt"><a id="masterThesisAnchor" href="#"><?=$this->transEsc('masterTheses')?></a></span>
        </div>
        <div class="col-md-3 col-xs-6">
          <span id="doctoralThesis" class="ntwrk-number">
            <div id="loading" style="margin-bottom: -.5em;text-align: center;">
              <img src="http://i.stack.imgur.com/Z4BUx.gif" alt="Carregando..." title="Carregando..." style="width: 5%">
            </div>
          </span><br>
          <span class="ntwrk-txt"><a id="doctoralThesisAnchor" href="#"><?=$this->transEsc('doctoralTheses')?></a> </span>          
        </div>
        <div class="col-md-3 col-xs-6">
          <span id="docSize" class="ntwrk-number ">
            <div id="loading" style="margin-bottom: -.5em;text-align: center;">
              <img src="http://i.stack.imgur.com/Z4BUx.gif" alt="Carregando..." title="Carregando..." style="width: 5%">
            </div>
          </span><br>
          <span class="ntwrk-txt" > <a id="" href="/vufind/Search/Results"><?=$this->transEsc('Documents')?></a></span>          
        </div>
      </div>
	  </div>
</div>

<!--

<div class="col-lg-2 col-sm-6" style="width: 15%; text-align: center;">
        <!--a href="/vufind/Search/Results?"></a>
          <span id="instSize" class="ntwrk-number">+30</span>
          <span class="ntwrk-txt"><br>
                <a href="<?=$this->url('institutions', []) ?>"><?=$this->transEsc('Institution')?> </a>
            </span>
      </div>
          <div  class="col-xs-4" style="width: 25%; text-align: center;">             
              <span id="masterThesis" class="ntwrk-number">+160.000</span><br>
              <span class="ntwrk-txt"><a id="masterThesisAnchor" href="#"><?=$this->transEsc('masterTheses')?></a></span>
            </div>
            <div class="col-xs-4" style="width: 25%; text-align: center;">              
              <span id="doctoralThesis" class="ntwrk-number">+400.000</span><br>
              <span class="ntwrk-txt"><a id="doctoralThesisAnchor" href="#"><?=$this->transEsc('doctoralTheses')?></a> </span>
          </div>          
          <div class="col-lg-2 col-sm-6" style="width: 30%; text-align: center;">             
              <span id="docSize" class="ntwrk-number ">+1.000.000</span><br>
              <span class="ntwrk-txt" > <a id="" href="/vufind/Search/Results"><?=$this->transEsc('Documents')?></a></span>
          </div>

-->



<? if (isset($facetList) && is_array($facetList)): ?>
  <!--div class="row">
    <? foreach ($facetList as $field => $details): ?>
      <? if (isset($this->hierarchicalFacets) && in_array($field, $this->hierarchicalFacets)): ?>
        <? $this->headScript()->appendFile('vendor/jsTree/jstree.min.js'); ?>
        <? $this->headScript()->appendFile('facets.js'); ?>
        <? $sort = isset($this->hierarchicalFacetSortOptions[$field]) ? $this->hierarchicalFacetSortOptions[$field] : ''; ?>
        <?
        $script = <<<JS
$(document).ready(function() {
  initFacetTree($('#facet_{$this->escapeHtml($field)}'), false);
});
JS;
        ?>
        <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
        <div class="facet <?=$field=='callnumber-first' ? 'col-sm-6' : 'col-sm-3' ?>">
          <h2><?=$this->transEsc('home_browse') . ' ' . $this->transEsc($details['label'])?></h2>
          <div id="facet_<?=$this->escapeHtml($field)?>" class="jstree-facet"
              data-facet="<?=$this->escapeHtml($field)?>"
              data-path="<?=$this->url($basicSearch)?>"
              data-exclude="0"
              data-operator="AND"
              data-exclude-title="<?=$this->transEsc('exclude_facet')?>"
              data-sort="all">
          </div>
        </div>
        <noscript>
      <? endif; ?>
      <? $sortedList = $this->sortFacetList($this->results, $field, $details['list'], $basicSearch); ?>
      <div class="<?=$field=='callnumber-first' ? 'col-sm-6' : 'col-sm-3' ?>">
        <h2><?=$this->transEsc('home_browse') . ' ' . $this->transEsc($details['label'])?></h2>
        <div class="row">
          <ul class="list-unstyled <?=$field == "callnumber-first" ? 'col-sm-6' : 'col-sm-12' ?>">
          <? /* Special case: two columns for LC call numbers... */ ?>
          <? if ($field == "callnumber-first"): ?>
            <? $i = 0; foreach ($sortedList as $url => $value): ?>
              <? if (!empty($value)): ?>
                <li><a href="<?=$url?>"><?=$this->escapeHtml($value)?></a></li>
              <? else: $i--; ?>
              <? endif; ?>
              <? if (++$i == 10): ?>
                </ul><ul class="list-unstyled col-sm-6">
              <? endif; ?>
            <? endforeach; ?>
          <? /* Special case: collections */ ?>
          <? elseif ($field == 'hierarchy_top_title'): ?>
            <? $i = 0; foreach ($sortedList as $url => $value): ?>
              <? if (++$i > 10): ?>
                <li><a href="<?=$this->url('collections-home')?>"><strong><?=$this->transEsc("More options")?>...</strong></a></li>
                <? break; ?>
              <? else: ?>
                <li><a href="<?=$this->url('collections-bytitle')?>?title=<?=urlencode($value)?>"><?=$this->escapeHtml($value)?></a></li>
              <? endif; ?>
            <? endforeach; ?>
          <? else: ?>
            <? $i = 0; foreach ($sortedList as $url => $value): ?>
              <? if (++$i > 10): ?>
                <li><a href="<?=$this->url($advSearch)?>"><strong><?=$this->transEsc("More options")?>...</strong></a></li>
                <? break; ?>
              <? elseif (!empty($value)): ?>
                <li><a href="<?=$url?>"><?=$this->escapeHtml($value)?></a></li>
              <? else: $i--; ?>
              <? endif; ?>
            <? endforeach; ?>
          <? endif; ?>
          </ul>
        </div>
      </div>
      <? if (isset($this->hierarchicalFacets) && in_array($field, $this->hierarchicalFacets)): ?>
        </noscript>
      <? endif; ?>
    <? endforeach; ?>
  </div-->

<? endif; ?>

<div class="row about">  
  <div class="col-md-6 md-margin-bottom-60" style="">
    <h3 style="color:#0a630a">Sobre a BDTD</h3>
      <p>O Ibict desenvolveu e coordena a Biblioteca Digital Brasileira de Teses e Dissertações (BDTD), que integra os sistemas de informação de teses e dissertações existentes nas instituições de ensino e pesquisa do Brasil, e também estimula o registro e a publicação de teses e dissertações em meio eletrônico. A BDTD, em parceria com as instituições brasileiras de ensino e pesquisa, possibilita que a comunidade brasileira de C&T publique e difunda suas teses e dissertações produzidas no País e no exterior, dando maior visibilidade à produção científica nacional.</p>
  </div>
  
  <div class="col-ms-6 col-xs-6 md-margin-bottom-60" style="">
  	<h3 style="color:#0a630a">Assista o vídeo sobre a BDTD</h3>
  	<iframe width="160" height="100" class="embed-responsive-item" src="//www.youtube.com/embed/8Xwa4pIz2rI" frameborder="0" ></iframe>
  	<p>Veja como a BDTD funciona.</p>
  </div>

</div>

<div id="services" class="container" >
  <div class="row" style="">
    <div class="col-md-1 col-xs-0">
    </div>
    <div class="col-md-2 col-xs-4">
      <a href="<?=$this->url('content-page', ['page' => 'participate']) ?>" ">
        <img class="partner-color" src="<?=$this->imageLink('imgParticipe.png') ?>" style="width: 70%;">
      </a>    
    </div>
    <div class="col-md-2 col-xs-4">
      <a href="<?=$this->url('content-page', ['page' => 'technology']) ?>">
        <img class="partner-color" src="<?=$this->imageLink('imgTec.png') ?>" style="width: 70%;">
      </a>    
    </div>
    <div class="col-md-2 col-xs-4">
      <a href="<?=$this->url('content-page', ['page' => 'statics']) ?>">
        <img class="partner-color" src="<?=$this->imageLink('imgIndicad.png') ?>" style="width: 70%;">
      </a>    
    </div>
    <div class="col-md-2 col-xs-4">
      <a href="<?=$this->url('content-page', ['page' => 'contact']) ?>">
        <img class="partner-color" src="<?=$this->imageLink('imgContato.png') ?>" style="width: 70%;">
      </a>    
    </div>
    <div class="col-md-2 col-xs-4">
      <a href="<?=$this->url('content-page', ['page' => 'faqs']) ?>">
        <img class="partner-color .img-responsive" src="<?=$this->imageLink('imgFAQ.png') ?>" style="width: 70%;">
      </a>
    </div>
  </div>
</div>



<!--div class="col-md-12 col-xs-4">
    <a href="<?=$this->url('content-page', ['page' => 'participate']) ?>" style="width: 13%;">
      <img class="partner-color" src="<?=$this->imageLink('imgParticipe.png') ?>" style="width: 13%;">
    </a>
    <a href="<?=$this->url('content-page', ['page' => 'technology']) ?>">
      <img class="partner-color" src="<?=$this->imageLink('imgTec.png') ?>" style="width: 13%;">
    </a>
    <a href="<?=$this->url('content-page', ['page' => 'statics']) ?>">
      <img class="partner-color" src="<?=$this->imageLink('imgIndicad.png') ?>" style="width: 13%;">
    </a>
    <a href="<?=$this->url('content-page', ['page' => 'contact']) ?>">
      <img class="partner-color" src="<?=$this->imageLink('imgContato.png') ?>" style="width: 13%;">
    </a>
    <a href="<?=$this->url('content-page', ['page' => 'faqs']) ?>">
      <img class="partner-color .img-responsive" src="<?=$this->imageLink('imgFAQ.png') ?>" style="width: 13%;">
    </a>
  </div-->


<div id="partnes" class="row" >
	<div class="col-xs-12">
		<div class="headline" style="width: 70%;">
			<h2 class="h2">Conheça também</h2>
		</div>
  </div>
	<div class="col-xs-4" style="text-align: center;">
    <a target="_blank" href="http://oasisbr.ibict.br">
      <img class="rounded float-left" src="<?=$this->imageLink('oasis.png') ?>" alt="" style="width:40%">
    </a>
	  <a target="_blank" href="http://www.lareferencia.info">
      <img class="rounded float-right" src="<?=$this->imageLink('laref.png') ?>" alt="La-referencia" style="width:40%">
    </a>
  </div>
  
  <div class="col-xs-4" style="text-align: center;">
    <a target="_blank" href="https://www.deposita.ibict.br">
      <img class="rounded float-left" src="<?=$this->imageLink('logoDeposita.png') ?>" alt="" style="width:35%">
      </a>
    <a target="_blank" href="http://www.ndltd.org/">
      <img class="rounded float-right" src="<?=$this->imageLink('ndltd.jpg') ?>" alt="" style="width:25%">
    </a>
  </div>
  <div class="col-xs-4" >
    <a target="_blank" href="http://www.ibict.br/">
      <img class="rounded float-left" src="<?=$this->imageLink('logo_ibict.png') ?>" alt="" style="width: 35%" >
    </a>
    <a target="_blank" href="https://www.rcaap.pt/">
      <img class="rounded float-right" src="<?=$this->imageLink('rcaap2.png') ?>" alt="" style="width: 45%" >
    </a>
  </div>
</div>
	
