<? $this->headTitle($this->translate('SNRD')); ?>

<div class="jumbotron franja-presentacion">
  <div class="container">
    <div class="row">
        <div class="col-sx-12 col-sm-6">
            <h1 class="header-snrd">Sistema Nacional de Repositorios Digitales</h1>
            <p class="subheader-snrd"><small><?= $this->transEsc('Open Access Argentine scientific publications') ?></small></p>
        </div>
        <div class="col-xs-12 col-sm-6">
            <div class="searchHomeContent">
            <h2><i class="fa fa-search"></i> <?= $this->transEsc('Search') ?></h2>
  <?
  $ilsStatusScript = <<<JS
$(document).ready(function() {
  $.ajax({
      dataType: 'json',
      method: 'GET',
      data: {'offlineModeMsg':'ils_offline_home_message'},
      url: VuFind.path + '/AJAX/JSON?method=getIlsStatus',
      success: function(response) {
          $('.searchHomeContent').prepend(response.data);
      }
  });
});
JS;
        ?>
            <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $ilsStatusScript, 'SET'); ?>
            <?=$this->context($this)->renderInContext("search/searchbox.phtml", ['ignoreHiddenFilterMemory' => true])?>
            <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, '$("#searchForm_lookfor").focus();', 'SET'); ?>
            </div>
        </div>
    </div>
  </div>
</div>

<div class="container main-info">
  <script>
    $.ajax({
      type: 'GET',
      url: '/vufind/api/v1/search?type=AllFields&page=0&limit=0&lng=<?= $this->layout()->userLang ?>',
      success: function (data) {
        $('#totalRecords').html(addSeparator(data.resultCount));
      }
    });
    $.ajax({
      type: 'GET',
      url: '/vufind/api/v1/search?type=AllFields&page=0&limit=0&lng=<?= $this->layout()->userLang ?>&facet[]=reponame_str',
      success: function (data) {
        $('#totalRepos').html(addSeparator(data.facets.reponame_str.length));
      }
    });
    $.ajax({
      type: 'GET',
      url: '/vufind/api/v1/search?type=AllFields&page=0&limit=0&lng=<?= $this->layout()->userLang ?>&facet[]=instname_str',
      success: function (data) {
        $('#totalInstitutions').html(addSeparator(data.facets.instname_str.length));
      }
    });
  </script>
  <div class="row">
    <div class="col-sm-12">
      <table class="stats-home table-responsive">
        <tr><td id="totalRecords"></td><td id="totalRepos"></td><td id="totalInstitutions"></td></tr>
        <tr><td><?= $this->transEsc('publications') ?></td><td><?= $this->transEsc('repositories') ?></td><td><?= $this->transEsc('institutions') ?></td></tr>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <h2>El SNRD</h2>

      <p class="text-justify"><?= $this->translate('home_intro_text1') ?></p>

      <p class="text-justify"><?= $this->translate('home_intro_text2') ?></p>

      <h2><?= $this->transEsc('Open Access') ?></h2>

      <p class="text-justify"><?= $this->translate('home_intro_text3') ?></p>

      <p class="text-justify"><?= $this->translate('home_intro_text4') ?></p>
    </div>
  </div>
  <div class="row">
    <div class=" col-sm-12 news-container">
      <h2><?= $this->transEsc('News') ?></h2>
      <br>
      <script>
        $.ajax({
          type: 'GET',
          url: 'http://biblio-int.mincyt.gob.ar/api/news',
          data: {'platform':3},
          beforeSend: function(){
            $('.carousel-inner').append('<i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i><span class="sr-only">Cargando listado...</span>');
          },
          success: function (data) {
            $.each(data, function (index, value) {
              $('.carousel-inner').append('<div class="item"><img src="http://biblio-int.mincyt.gob.ar/images/news/'+value.id+'_.jpg" class="img-responsive"><div class="carousel-caption"><h4><a href="http://www.biblioteca.mincyt.gob.ar/novedades/ver?id='+value.id+'" target="_blank">' + value.headline + '</a></h4></div></div>');
              $('.carousel-inner div:first-child').addClass('active');
            })
          }
        })
      </script>
      <div class="col-sm-8">
        <div id="carousel" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carousel" data-slide-to="0" class="active"></li>
            <li data-target="#carousel" data-slide-to="1"></li>
            <li data-target="#carousel" data-slide-to="2"></li>
            <li data-target="#carousel" data-slide-to="3"></li>
            <li data-target="#carousel" data-slide-to="4"></li>
          </ol>

          <div class="carousel-inner" role="listbox"></div>

          <a class="left carousel-control" href="#carousel" data-slide="prev">
           <i class="fa fa-chevron-left fa-3x"></i>
          </a>
          <a class="right carousel-control" href="#carousel" data-slide="next">
           <i class="fa fa-chevron-right fa-3x"></i>
          </a>
        </div>
      </div>
      <div class="col-sm-4">
        <h2 class="visible-xs">Twitter</h2>
        <div class="twitter-container">
          <a class="twitter-timeline" href="https://twitter.com/becyt_mincyt/lists/TwitterBecyt" data-chrome="noheader nofooter noborders" data-tweet-limit="5" data-link-color="#FCB415"></a>
        </div>
      </div>
    </div>
  </div>
  <h2><?= $this->transEsc('We\'re part of') ?></h2>
  <div class="row miembrosde">
    <div class="col-xs-12 col-sm-6 text-center">
      <a href="http://lareferencia.info" target="_blank">
        <img class="logo" src="http://www.lareferencia.info/joomla/images/logo.png" alt="lareferencia" />
      </a>
    </div>
    <div class="col-xs-12 col-sm-6 text-center">
      <a href="https://www.coar-repositories.org/" target="_blank">
        <img class="logo" src="https://www.coar-repositories.org/wp-content/themes/coarpress/img/coar-logo.png" alt="COAR" />
      </a>
    </div>
  </div>
</div>
<script>window.twttr = (function (d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0],
            t = window.twttr || {};
    if (d.getElementById(id))
      return t;
    js = d.createElement(s);
    js.id = id;
    js.src = "https://platform.twitter.com/widgets.js";
    fjs.parentNode.insertBefore(js, fjs);

    t._e = [];
    t.ready = function (f) {
      t._e.push(f);
    };

    return t;
  }(document, "script", "twitter-wjs"));
</script>