

<?
   // Set default value if necessary:
   if (!isset($this->searchClassId)) {
       $this->searchClassId = 'Solr';
   }
   
   // Load search actions and settings (if any):
   $options = $this->searchOptions($this->searchClassId);
   $handlers = $this->searchbox()->getHandlers(
       $this->searchClassId,
       isset($this->searchIndex) ? $this->searchIndex : null
   );
   $handlerCount = count($handlers);
   $basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
   $searchHome = $options->getSearchHomeAction();
   $advSearch = $options->getAdvancedSearchAction();
   $lastSort = $this->searchMemory()->getLastSort($this->searchClassId);
   $lastLimit = $this->searchMemory()->getLastLimit($this->searchClassId);
   $ignoreHiddenFilterMemory = isset($this->ignoreHiddenFilterMemory) && $this->ignoreHiddenFilterMemory;
   $ignoreHiddenFiltersInRequest = isset($this->ignoreHiddenFiltersInRequest) && $this->ignoreHiddenFiltersInRequest;
   $hiddenFilters = $this->searchtabs()->getHiddenFilters($this->searchClassId, $ignoreHiddenFilterMemory, $ignoreHiddenFiltersInRequest);
   if (empty($hiddenFilters) && !$ignoreHiddenFilterMemory) {
       $hiddenFilters = $this->searchMemory()->getLastHiddenFilters($this->searchClassId);
       if (empty($hiddenFilters)) {
           $hiddenFilters = $this->searchtabs()->getHiddenFilters($this->searchClassId);
       }
   }
   $hiddenFilterParams = $this->searchtabs()->getCurrentHiddenFilterParams($this->searchClassId, $ignoreHiddenFilterMemory, '?');
   ?>
<? $searchTabs = $this->searchtabs()->getTabConfig($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType, $hiddenFilters); ?>
<? if ($this->searchType == 'advanced'): ?>
<div class="navbar-form navbar-left flip">
   <? $tabs = $this->context($this)->renderInContext('search/searchTabs', ['searchTabs' => $searchTabs['tabs']]); ?>
   <? if (!empty($tabs)): ?><?=$tabs ?>
   <div class="tab-content clearfix">
      <? endif; ?>
      <p class="adv_search_terms"><?=$this->transEsc("Your search terms")?> : "<strong><?=$this->escapeHtml($this->lookfor)?></strong>"</p>
      <p class="adv_search_links">
         <a href="<?=$this->url($advSearch)?>?edit=<?=$this->escapeHtmlAttr($this->searchId)?>"><?=$this->transEsc("Edit this Advanced Search")?></a> |
         <a href="<?=$this->url($advSearch) . $hiddenFilterParams?>"><?=$this->transEsc("Start a new Advanced Search")?></a> |
         <a href="<?=$this->url($searchHome) . $hiddenFilterParams?>"><?=$this->transEsc("Start a new Basic Search")?></a>
      </p>
      <? if (!empty($tabs)): ?>
   </div>
   <? endif; ?>
</div>
<? else: ?>
<div style="background-image: url('/images/placa_buscador/fondo.jpg'); background-size: 100%;">
   <div class="row">
      <div class="col-lg-12 placa-home-title">EXPLORA LAS PUBLICACIONES CIENTÍFICAS DE <br>AMÉRICA LATINA EN ACCESO ABIERTO</div>
   </div>
   <div class="row form-home">
      <form action="/vufind/Search/Results" autocomplete="on" method="get" name="searchForm" id="searchForm" class="form-inline">
         <div class="col-lg-2 col-sm-12 no-padding">&nbsp;</div>
         <div class="col-lg-4 col-sm-12 no-padding">
            <input id="searchForm_lookfor" class="searchForm_lookfor form-control search-query autocomplete searcher:Solr searchome" type="text" name="lookfor" value="">
            <!--input name="lookfor" type="text" value="" id="searchForm_lookfor" class="form-control search-query searcher searchome" placeholder="Ingresar texto..."-->
         </div>
         <div class="col-lg-2 hidden-sm hidden-xs no-padding">
            <select name="type" id="searchForm_type" class="form-control selector" data-native-menu="false">
               <option value="AllFields">Todos los Campos</option>
               <option value="Title">Título</option>
               <option value="Author">Autor</option>
               <option value="Subject">Materia</option>
               <option value="Network_name">País</option>
            </select>
         </div>
         <div class="col-lg-1 col-sm-12 no-padding"><button type="submit" id="submit-home" class="btn btn-primary buscarbtn">Buscar</button></div>
         <div class="col-lg-1 col-sm-12 no-padding"><a href="/vufind/Search/Advanced" id="advance-search" class="btn btn-link advanced">Avanzada</a></div>
         <div class="col-lg-2 col-sm-12 no-padding">&nbsp;</div>
      </form>
   </div>
   <div class="row">
<div class="col-lg-12 content-datos">
         <div class="col-lg-2 col-sm-12 no-padding">&nbsp;</div>
         <div class="col-lg-2 boxslider no-padding dropdown">
            <div class="box-blue dropdown-toggle" data-toggle="dropdown">
               <h3>9</h3>
               <h4>NODOS NACIONALES</h4>
            </div>
            <ul class="dropdown-menu">
               <li><a href="/vufind/Search/Results?lookfor=network_acronym%3AAR">Argentina</a></li>
               <li><a href="/vufind/Search/Results?lookfor=network_acronym%3ABR">Brasil</a></li>
               <li><a href="/vufind/Search/Results?lookfor=network_acronym%3ACL">Chile</a></li>
               <li><a href="/vufind/Search/Results?lookfor=network_acronym%3ACO">Colombia</a></li>
               <li><a href="/vufind/Search/Results?lookfor=network_acronym%3ACR">Costa Rica</a></li>
               <li><a href="/vufind/Search/Results?lookfor=network_acronym%3AEC">Ecuador</a></li>
               <li><a href="/vufind/Search/Results?lookfor=network_acronym%3ASV">El Salvador</a></li>
               <li><a href="/vufind/Search/Results?lookfor=network_acronym%3AMX">México</a></li>
               <li><a href="/vufind/Search/Results?lookfor=network_acronym%3APE">Perú</a></li>
               <!--li><a href="/vufind/Search/Results?lookfor=network_acronym%3AVE">Venezuela</a></li-->
            </ul>
         </div>
         <div class="col-lg-2 boxslider no-padding">
            <div class="box-blue-light">
               <h3><a id="totalRecords" href="/vufind/Search/Results?lookfor=*%3A*"></a></h3>
               <h4><a href="/vufind/Search/Results?lookfor=*%3A*">DOCUMENTOS</a></h4>
            </div>
         </div>
         <div class="col-lg-2 boxslider no-padding">
            <div class="box-blue">
               <div class="col-lg-12 boxslider2">
                  <h4><a id="article" href="/vufind/Search/Results?lookfor=format%3Aarticle"></a></h4>
                  <h5><a href="/vufind/Search/Results?lookfor=format%3Aarticle">ARTÍCULOS</a></h5>
               </div>
               <div class="col-lg-12 boxslider2">
                  <h4><a id="report" href="/vufind/Search/Results?lookfor=format%3Areport"></a></h4>
                  <h5><a href="/vufind/Search/Results?lookfor=format%3Areport">REPORTES</a></h5>
               </div>
            </div>
         </div>
         <div class="col-lg-2 boxslider no-padding">
            <div class="box-blue-light ">
               <div class="col-lg-12 boxslider2">
                  <h4><a id="doctoralThesis" href="/vufind/Search/Results?lookfor=format%3AdoctoralThesis"></a></h4>
                  <h5><a href="/vufind/Search/Results?lookfor=format%3AdoctoralThesis">TESIS DE DOCTORADO</a></h5>
               </div>
               <div class="col-lg-12 boxslider2">
                  <h4><a id="masterThesis" href="/vufind/Search/Results?lookfor=format%3AmasterThesis"></a></h4>
                  <h5><a href="/vufind/Search/Results?lookfor=format%3AmasterThesis">TESIS DE MAESTRÍA</a></h5>
               </div>
            </div>
         </div>
         <div class="col-lg-2 col-sm-12 no-padding">&nbsp;</div>
      </div>
   </div>
</div>
<!--form id="searchForm" class="searchForm navbar-form navbar-left flip" method="get" action="<?=$this->url($basicSearch)?>" name="searchForm" autocomplete="off">
   <?= $this->context($this)->renderInContext('search/searchTabs', ['searchTabs' => $searchTabs['tabs']]); ?>
   <? $placeholder = $this->searchbox()->getPlaceholderText(isset($searchTabs['selected']['id']) ? $searchTabs['selected']['id'] : null); ?>
   <input id="searchForm_lookfor" class="searchForm_lookfor form-control search-query<? if($this->searchbox()->autocompleteEnabled($this->searchClassId)):?> autocomplete searcher:<?=$this->escapeHtmlAttr($this->searchClassId) ?><? endif ?>" type="text" name="lookfor" value="<?=$this->escapeHtmlAttr($this->lookfor)?>"<? if ($placeholder): ?> placeholder="<?=$this->transEsc($placeholder) ?>"<? endif ?> />
   <? if ($handlerCount > 1): ?>
     <select id="searchForm_type" class="searchForm_type form-control" name="type" data-native-menu="false">
       <? foreach ($handlers as $handler): ?>
         <option value="<?=$this->escapeHtmlAttr($handler['value'])?>"<?=$handler['selected'] ? ' selected="selected"' : ''?>><?=$handler['indent'] ? '-- ' : ''?><?=$this->transEsc($handler['label'])?></option>
       <? endforeach; ?>
     </select>
   <? elseif ($handlerCount == 1): ?>
     <input type="hidden" name="type" value="<?=$this->escapeHtmlAttr($handlers[0]['value'])?>" />
   <? endif; ?>
   <button type="submit" class="btn btn-primary"><i class="fa fa-search" aria-hidden="true"></i> <?=$this->transEsc("Find")?></button>
   <? if ($advSearch): ?>
     <a href="<?=$this->url($advSearch) . ((isset($this->searchId) && $this->searchId) ? '?edit=' . $this->escapeHtmlAttr($this->searchId) : $hiddenFilterParams) ?>" class="btn btn-link" rel="nofollow"><?=$this->transEsc("Advanced")?></a>
   <? endif; ?>
   <? if ($geoUrl = $this->geocoords()->getSearchUrl($options)) : ?>
       <a href="<?=$geoUrl ?>" class="btn btn-link"><?=$this->transEsc('Geographic Search')?></a>
   <? endif; ?>
   
   <? $shards = $options->getShards(); if ($options->showShardCheckboxes() && !empty($shards)): ?>
     <?
      $selectedShards = isset($this->selectedShards)
          ? $this->selectedShards : $options->getDefaultSelectedShards();
      ?>
     <br />
     <? foreach ($shards as $shard => $val): ?>
       <? $isSelected = empty($selectedShards) || in_array($shard, $selectedShards); ?>
         <input type="checkbox" <?=$isSelected ? 'checked="checked" ' : ''?>name="shard[]" value='<?=$this->escapeHtmlAttr($shard)?>' /> <?=$this->transEsc($shard)?>
     <? endforeach; ?>
   <? endif; ?>
   <?
      $filterDetails = $this->searchbox()->getFilterDetails(
          isset($this->filterList) && is_array($this->filterList) ? $this->filterList : [],
          isset($this->checkboxFilters) && is_array($this->checkboxFilters) ? $this->checkboxFilters : []
      );
      ?>
   <? if ((isset($hasDefaultsApplied) && $hasDefaultsApplied) || !empty($filterDetails)): ?>
     <? $defaultFilterState = $options->getRetainFilterSetting() ? ' checked="checked"' : ''; ?>
     <div class="checkbox">
       <label>
         <input type="checkbox"<?=$defaultFilterState?> class="searchFormKeepFilters"/>
         <?=$this->transEsc("basic_search_keep_filters")?>
       </label>
     </div>
     <div class="hidden">
       <? foreach ($filterDetails as $current): ?>
         <input class="applied-filter" id="<?=$this->escapeHtmlAttr($current['id'])?>" type="checkbox"<?=$defaultFilterState?> name="filter[]" value="<?=$this->escapeHtmlAttr($current['value'])?>" />
         <label for="<?=$this->escapeHtmlAttr($current['id'])?>"><?=$this->escapeHtml($current['value'])?></label>
       <? endforeach; ?>
       <? if (isset($hasDefaultsApplied) && $hasDefaultsApplied): ?>
        
         <input class="applied-filter" id="dfApplied" type="checkbox" name="dfApplied" value="1"<?=$defaultFilterState?> />
       <? endif; ?>
     </div>
   <? endif; ?>
   <? foreach ($hiddenFilters as $key => $filter): ?>
     <? foreach ($filter as $value): ?>
       <input type="hidden" name="hiddenFilters[]" value="<?=$this->escapeHtmlAttr($key) . ':' . $this->escapeHtmlAttr($value)?>" />
     <? endforeach; ?>
   <? endforeach; ?>
   <?
      /* Show hidden field for active search class when in combined handler mode. */
      if ($this->searchbox()->combinedHandlersActive()) {
        echo '<input type="hidden" name="activeSearchClassId" value="' . $this->escapeHtmlAttr($this->searchClassId) . '" />';
      }
      /* Load hidden limit preference from Session */
      if (!empty($lastLimit)) {
        echo '<input type="hidden" name="limit" value="' . $this->escapeHtmlAttr($lastLimit) . '" />';
      }
      if (!empty($lastSort)) {
        echo '<input type="hidden" name="sort" value="' . $this->escapeHtmlAttr($lastSort) . '" />';
      }
      ?>
   </form-->
<? endif; ?>
<script>
   $.ajax({
     type: 'GET',
     url: '/vufind/api/v1/search?type=AllFields&page=0&limit=0&lng=<?= $this->layout()->userLang ?>',
     success: function (data) {
       $('#totalRecords').html(addSeparator(data.resultCount));
     }
   });
   $.ajax({
     type: 'GET',
     url: '/vufind/api/v1/search?type=AllFields&page=0&limit=0&lng=<?= $this->layout()->userLang ?>&facet[]=format',
     success: function (data) {
       var format = {};
   
       for (var i=0; i< data.facets.format.length; i++) {
         var facet = data.facets.format[i];
         format[ facet.value ] = facet.count;
       }
   
   
       $('#article').html(addSeparator(format['article']));
       $('#masterThesis').html(addSeparator(format['masterThesis']));
       $('#doctoralThesis').html(addSeparator(format['doctoralThesis']));
       $('#report').html(addSeparator(format['report']));
   
     }
   });
   
</script>

