<div class="clearfix">&nbsp;</div>
<footer class="hidden-print">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 footer-contact">
        <p style="font-size: 10px;">2011, Consorcio de Bibliotecas Universitarias de El Salvador - CBUES
        <br>
Segundo Nivel de la Biblioteca "P. Florentino Idoate, S.J." Universidad Centroamericana José Simeón Cañas - UCA 
<br>
Boulevard Los Próceres San Salvador, El Salvador, Centro América, Apartado Postal 01-168, Teléfono: (503) 2210-6600 Ext. 304
        </p>
      </div>
      <div class="col-sm-4 text-center social-media">
      <p>
        <a class="socialMediaLink" href="https://www.facebook.com/cbuesOficial/" target="_blank"><i class="fa fa-facebook-square fa-fw fa-2x" aria-hidden="true"></i></a>
        <a class="socialMediaLink" href="https://twitter.com/CBUESoficial" target="_blank"><i class="fa fa-twitter-square fa-fw fa-2x" aria-hidden="true"></i></a>
        
      </p>
      </div>
    </div>
  </div>
</footer>
