<? $path = $this->CurrentPath(); ?>

<div class="container logos hidden-xs hidden-sm">
  <div class="row">
    <div class="col-md-6 text-left logo-repo">
      <img class="img-responsive" src="/vufind/themes/bootstrap3/images/logo.png" width="250" />
    </div>
    <div class="col-md-3 text-right logo-inst">
      <img class="img-responsive" src="/vufind/themes/bootstrap3/images/logomined.png" alt="" />
    </div>
    <div class="col-md-3 text-right logo-inst">
      <img class="img-responsive" src="/vufind/themes/bootstrap3/images/logocbues.png" alt="CBUES" />
    </div>
  </div>
</div>

<nav class="navbar">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand lang-<?=$this->layout()->userLang ?> visible-xs-block visible-sm-block" href="<?=$this->url('home')?>">REDES</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li <?= $path == '/vufind/' ? 'class="active"' : '' ?>><a href="<?=$this->url('home')?>"><?=$this->transEsc("Home")?></a></li>
        <li <?= $path == '/vufind/Content/about' ? 'class="active"' : '' ?>><a href="<?=$this->url('content-page', ['page' => 'about']) ?>"><?=$this->transEsc("Institutional")?></a></li>
        <li <?= $path == '/vufind/Content/browse' ? 'class="active"' : '' ?>><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc("Búsqueda")?></a></li>
        <li <?= $path == '/vufind/Content/repos' ? 'class="active"' : '' ?>><a href="<?=$this->url('content-page', ['page' => 'repos']) ?>"><?=$this->transEsc("Repositorios")?></a></li>
        <li <?= $path == '/vufind/Content/stats' ? 'class="active"' : '' ?>><a href="<?=$this->url('content-page', ['page' => 'stats']) ?>"><?=$this->transEsc("Estadísticas")?></a></li>
        <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
            <li class="language dropdown">
              <form method="post" name="langForm" id="langForm">
                <input type="hidden" name="mylang"/>
              </form>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Idioma")?> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                  <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
                <? endforeach; ?>
              </ul>
            </li>
          <? endif; ?>
      </ul>
    </div>
  </div>
</nav>

<? if ($this->layout()->searchbox !== false): ?>
<div class="container">
  <div class="search navbar navbar-right">
    <nav class="nav searchbox hidden-print">
      <?=$this->layout()->searchbox ?>
    </nav>
  </div>
</div>
<? endif; ?>
<div class="clearfix"></div>
