<div class="row" id="open">
	<div class="col-sm-12">
		<h2 class="titleText">Acesso Aberto Brasil</h2>
		<h4><span class="subTitText"> FIQUE POR DENTRO DAS INICIATIVAS EM PROL DO ACESSO ABERTO À INFORMAÇÃO CIENTÍFICA COORDENADAS PELO IBICT!</span></h4>
		<p class="text">
			A Biblioteca Digital Brasileira de Teses e Dissertações (BDTD) é um dos sistemas que faz parte do Programa Brasileiro de Acesso Aberto à Informação Científica, coordenado pelo Instituto Brasileiro de Informação em Ciência e Tecnologia (IBICT). A BDTD foi o primeiro sistema a utilizar os conceitos de Arquivos Abertos, sendo assim, modelo para o desenvolvimento de outros produtos / serviços. 

			As ações em prol do Acesso Aberto à Informação Científica, como as notícias da BDTD, podem ser acompanhadas pela página do Programa no Facebook. Acompanhe! 
			</br></br>
			<a href="https://www.facebook.com/acessoabertobrasil">
				<img src="<?=$this->imageLink('facebook.png') ?>" style="width:3%;"> 
			</a>
		</p>	
	</div>
</div>