

<div class="row" id="contact">
	<div class="col-sm-12">
		<h2 class="titleText">Contato</h2>
		<h4><span class="subTitText"> ENTRE EM CONTATO COM A EQUIPE BDTD</span></h4>
		<p class="text">
			<span class="glyphicon glyphicon-envelope fa-1x"></span> 
			<span style="text-decoration: underline">equipebdtd@ibict.br </span> </br>
			Recomendamos sempre a utilização deste email, em detrimento do uso dos emails dos técnicos da BDTD, uma vez que estes técnicos podem ser alterados.
			</br></br>
			<span class="glyphicon glyphicon-phone-alt fa-1x"></span>  + 55 61 3217-6449 | 6249
			</br></br>
			
			<a href="https://www.google.com.br/maps/place/Instituto+Brasileiro+de+Informa%C3%A7%C3%A3o+em+Ci%C3%AAncia+e+Tecnologia+(IBICT)/@-15.804474,-47.881706,15z/data=!4m5!3m4!1s0x0:0x9bf85bfdfd4252d0!8m2!3d-15.804474!4d-47.881706"
				target="_blank">
				<span class="fa fa-map-marker fa-2x"></span>
			</a>
			Coordenação do Laboratório de Metodologias de Tratamento e Disseminação da Informação (COLAB)<br>
			Coordenação Geral de Pesquisa e Manutenção de Produtos Consolidados (CGPC)<br>
			Instituto Brasileiro de Informação em Ciência e Tecnologia (IBICT) <br>
			SAUS Quadra 05 Lote 6 Bloco H – Asa Sul, Brasília, Brasil | CEP: <br>
			</div>
		</p>	
	</div>
</div>
