
<style type="text/css">
	
	.iconRed{
		color: red;		
	}

	.iconGreen{
		color: #0a630a;		
	}

	.disable{
		display: none !important;		
	}

	.active{
		display: '' !important;
		
	}

</style>

<div class="row" id="work" style="margin-bottom: 5em">
	<div class="col-xs-12">
		<h1 class="titleText">Critérios para coleta</h1>
	</div>
	<div class="col-xs-12" style="padding-left: 7em;">
			<ul>
				<li>
					<h3>Critérios Gerais (para todos os provedores de conteúdo)<a id="Gerais" href="#" onclick="showDesc(this);"> <span class="fa fa-plus-circle fa-1x iconGreen" ></span></a></h3>
				</li>
					<span class="Gerais disable">
						<ul>
							<li>Fazer uso do protocolo OAI-PMH (Open Archives Initiative - Protocol for Metadata Harvesting) ou compatível;</li>
							<li>Gerenciar ou publicar informação de natureza científica e/ou tecnológica;</li>
							<li>Os recursos de informação devem estar disponíveis em texto completo disponível no próprio provedor de conteúdos;</li>
							<li>Adotar o esquema de metadados Dublin Core ou compatível;</li>
							<li>Manter conexão permanente com a Internet.  </li>
							<li>Adoção de metadado que especifique o tipo de documento (por exemplo: dc:type), cujo preenchimento obedeça às orientações da equipe coordenadora (usar vocabulário controlado DRIVER);</li>
							<li>Para todos os provedores de conteúdos, exige-se um conjunto mínimo de metadados (título, autor, resumo, palavras-chave, ano da publicação – dc:issued / fechado, tipo de documento, idioma, avaliados ou não pelos pares);</li>					
						</ul>
					</span>
				<li>
					<h3>Critérios específicos para Periódicos Científicos<a id="Periodicos" href="#" onclick="showDesc(this);"> <span class="fa fa-plus-circle fa-1x iconGreen" ></span></a>
					</h3>
				</li>
				<span class="Periodicos disable">
						 <ul>
							<li>Fazer parte da SciELO;</li>
							<li>Registrar políticas no Diadorim;</li>
						</ul>

						 <h3>Ou</h3>

						 <ul>
							<li>Possuir ISSN;</li>
							<li>Caráter científico e/ou tecnológico;</li>
							<li>Adoção de arbitragem por pares;</li>
							<li>Indicação explícita do conselho editorial ou similar e que este possua caráter exógeno;</li>
							<li>Regularidade na periodicidade;</li>
							<li>Possuir, no mínimo, três números publicados;</li>
							<li>Acesso aos artigos deve ser gratuito e irrestrito;</li>
							<li>Registrar políticas no Diadorim;</li>
						</ul>

						<strong>
							<h3>Observação:</h3>
							<p>Revistas cadastradas no Diadorim são automaticamente avaliadas para a coleta do portal oasisbr. Para saber mais sobre o Diadorim acesse 
							<a href="http://diadorim.ibict.br/" target="_blank">aqui </a></p>
						</strong>
				</span>
				<li>
					<h3>Critérios para Teses e Dissertações Eletrônicas<a id="bdtd" href="#" onclick="showDesc(this);"> <span class="fa fa-plus-circle fa-1x iconGreen" ></span></a></h3>
				</li>
				<span class="bdtd disable">
					<ul>
						<li>Ser coletado pela Biblioteca Digital Brasileira de Teses e Dissertações.</li>
					</ul>
				</span>
				<li>
					<h3>Critérios para Repositórios de Conferências (anais eletrônicos)
					<a id="Repositorios" href="#" onclick="showDesc(this);"> <span class="fa fa-plus-circle fa-1x iconGreen" ></span></a></h3>
				</li>
				<span class="Repositorios disable">
						<ul>
							<li>O acesso aos trabalhos deve ser gratuito;</li>
							<li>O evento deve ser de natureza científica e/ou tecnológica;</li>
							<li>Adoção de arbitragem científica;</li>
							<li>Indicação explícita do conselho editorial ou similar e que este possua caráter exógeno/multinstitucional;</li>
							<li>O acesso aos antigos deve ser gratuito e irrestrito. </li>
						</ul>
				</span>
			<ul>
		
	</div>	
</div>


<script type="text/javascript">
	function showDesc(id){		
		
		var field = "." + id.id;
		$(field).show(100).delay(2000);

		$('#' + id.id +'> span').toggleClass('fa-minus-circle iconGreen iconRed');
		$('.' + id.id).toggleClass('disable active');		
	}
</script>