    
<div class="row" id="networks">
	<div class="col-xs-12" style="padding-left: 7em;">
		<h2 class="titleText">Fontes Coletadas</h2>
 	
		<h4 style="margin: 2.5em 0 2.5em 0;">
			<strong><a class="external-link" href="http://wiki.ibict.br/index.php/Bibliotecas_Digitais_de_Teses_e_Disserta%C3%A7%C3%B5es" target="_blank">Bibliotecas Digitais de Teses e Dissertações</a></strong>	
		</h>
		<h4 style="margin: 2.5em 0 2.5em 0;">
			<strong><a class="external-link" href="http://www.rcaap.pt/" target="_blank">Repositório Científico de Acesso Aberto de Portugal - RCAAP</a></strong>
		</h4>

		<div class="row" style="text-align: center;margin: 2.5em 0 2.5em 0;">
			<iframe src="https://www.google.com/maps/d/embed?mid=z0zroFicy1lI.kv0dg-Nu3CQ8" width="640" height="480" style=""></iframe>			
		</div>
	</div>
</div>