<?
$data = $this->driver->getRawData();

?>
<div class="media-body">

    <h1 class="h2"><?= $this->escapeHTML($data['title']) ?></h2>
    <p>&nbsp;</p>
    <dl class="dl-horizontal">
      <dt><?=  $this->transEsc('Authors') ?></dt>
      <dd><? $summAuthors = $data['author_facet']; ?>
        <? $authorCount = count($summAuthors);
        foreach ($summAuthors as $i => $summAuthor):
          ?>
          <a href="<?= $this->record($this->driver)->getLink('author', $this->highlight($summAuthor, null, true, false)) ?>"><?= $this->escapeHTML($summAuthor) ?></a><?= $i + 1 < $authorCount ? '; ' : '' ?>
        <? endforeach; ?>
      </dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><?=  $this->transEsc('Format') ?></dt>
      <dd><?= $this->transEsc($data['format'][0]) ?></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><?= $this->transEsc('Status')?></dt>
      <dd><?= $this->transEsc($data['status_str'])?></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><?=  $this->transEsc('Publication Year') ?></dt>
      <dd><?= $data['publishDate'][0] ?></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><?= $this->transEsc('Country')?></dt>
      <dd><?= $data['network_name_str']?></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><?= $this->transEsc('Institution')?></dt>
      <dd><?= $data['instname_str']?></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><?= $this->transEsc('Repository')?></dt>
      <dd><?= $data['reponame_str']?></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><?=  $this->transEsc('Description') ?></dt>
      <dd><?=$data['description']?> </dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><?= $this->transEsc('Language')?></dt>
      <dd><?= $this->transEsc($data['language'][0])?></dd>
    </dl>
   
    <dl class="dl-horizontal">
      <dt><?= $this->transEsc('OAI Identifier')?></dt>
      <dd><?=$data['oai_identifier_str']?> </dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><?= $this->transEsc('Get full text')?></dt>
      <dd><? foreach($data['url'] as $url):?><a href="<?= $url ?>" target="_blank"><?= $url ?></a><br><? endforeach;?></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><?= $this->transEsc('Rights')?></dt>
      <dd><?= $this->transEsc($data['eu_rights_str_mv'][0]) ?></dd>
    </dl>
    <!--dl class="dl-horizontal">
      <dt><?= $this->transEsc('License')?></dt>
      <dd><?= $data['rights_invalid_str_mv'][0] ?></dd>
    </dl-->

    <dl class="dl-horizontal">
      <dt><?= $this->transEsc('Topic')?></dt>
      <dd><? foreach($data['topic'] as $topic):?><?= $topic ?><br><? endforeach; ?></dd>
    </dl>
</div>
