<h4><?=$this->transEsc('Similar Items')?></h4>
<? $similarRecords = $this->related->getResults(); ?>
<? if (!empty($similarRecords)): ?>
  <ul class="list-group">
    <? foreach ($similarRecords as $data): ?>
      <? $formats = $data->getFormats(); ?>
      <li class="list-group-item">
        <i class="flaticon-<?= $formats[0] ?>" title="<?= $this->transEsc($formats[0]) ?>"></i>
        <p class="text-justify">
          <? $authors = $data->getPrimaryAuthors(); if (!empty($authors)): ?>
            <?=$this->escapeHtml($authors[0]);?>; 
            <? $authorCount = count($data->getSecondaryAuthors()); ?>
            <? foreach($data->getSecondaryAuthors() as $i => $a):?>
              <?= $a ?><?= $i + 1 < $authorCount ? '; ' : substr($a,-1) == '.' ? '': '. ' ?>
            <? endforeach ?>
          <? endif; ?>

          <? $pubDates = $data->getPublicationDates(); if (!empty($pubDates)): ?>
            (<?=$this->escapeHtml($pubDates[0])?>)
          <? endif; ?>

          <a href="<?=$this->recordLink()->getUrl($data)?>">
            <?=$this->escapeHtml($data->getTitle()) ?>
          </a>
        </p>
      </li>
    <? endforeach; ?>
  </ul>
<? else: ?>
  <p><?=$this->transEsc('Cannot find similar records')?></p>
<? endif; ?>
