<!--div class="row">
  <div class="col-sm-4">
    <p><strong><?=$this->transEsc('Search Options')?></strong></p>
    <ul>
      <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
      <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
    </ul>
  </div>
  <div class="col-sm-4">
    <p><strong><?=$this->transEsc('Find More')?></strong></p>
    <ul>
      <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
      <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
      <li><a href="<?=$this->url('channels-home')?>"><?=$this->transEsc('channel_explore')?></a></li>
      <li><a href="<?=$this->url('search-reserves')?>"><?=$this->transEsc('Course Reserves')?></a></li>
      <li><a href="<?=$this->url('search-newitem')?>"><?=$this->transEsc('New Items')?></a></li>
    </ul>
  </div>
  <div class="col-sm-4">
    <p><strong><?=$this->transEsc('Need Help?')?></strong></p>
    <ul>
      <li><a href="<?=$this->url('help-home')?>?topic=search&amp;_=<?=time() ?>" data-lightbox class="help-link"><?=$this->transEsc('Search Tips')?></a></li>
      <li><a href="<?=$this->url('content-page', ['page' => 'asklibrary']) ?>"><?=$this->transEsc('Ask a Librarian')?></a></li>
      <li><a href="<?=$this->url('content-page', ['page' => 'faq']) ?>"><?=$this->transEsc('FAQs')?></a></li>
    </ul>
  </div>
</div-->

<div class="row" >
  <div class="col-xs-6">
    <a href="www.ibict.br">
      <img alt="Ibict" src="<?=$this->imageLink('logo_ibict.png') ?>" style="width:150px; padding-top:.5em;"/> 
    </a>
    <p style="float: right;margin: 1em 4em 0 0;text-align: left;padding-top: 0.81em;color:#9a9a9a;font-size:12px">
      Instituto Brasileiro de Informação em Ciência e Tecnologia <br/>
      SAUS Quadra 05 Lote 06 Bloco H – Asa Sul, Brasília, DF
    </p>
  </div>
  <div class="col-xs-6" >
    <a href="http://www.mcti.gov.br/" target="_blank">
      <img alt="MCTI" src="<?=$this->imageLink('logoMCT.png') ?>" style="width:250px; padding-top:1em;float:right">
    </a>    
  </div>
</div>    
