
<? $account = $this->auth()->getManager(); ?>



<div id="barra-brasil">
  <div id="wrapper-barra-brasil">
    <div class="brasil-flag">
      <a href="http://brasil.gov.br" class="link-barra">Brasil</a>
    </div>
    <span class="acesso-info"><a href="http://www.servicos.gov.br/?pk_campaign=barrabrasil" class="link-barra" id="barra-brasil-orgao">Serviços</a></span>
    <nav>
      <ul class="list">
        <li>
          <a href="#" id="menu-icon"></a>
        </li>
        <li class="list-item first">
          <a href="http://brasil.gov.br/barra#participe" class="link-barra">Participe</a>
        </li>
        <li class="list-item">
          <a href="http://brasil.gov.br/barra#acesso-informacao" class="link-barra">Acesso à informação</a>
        </li>
        <li class="list-item">
          <a href="http://www.planalto.gov.br/legislacao" class="link-barra">Legislação</a>
        </li>
        <li class="list-item last last-item">
          <a href="http://brasil.gov.br/barra#orgaos-atuacao-canais" class="link-barra">Canais</a>
        </li>
      </ul>
    </nav>
    <a class="logo-vlibras" href="http://www.vlibras.gov.br/" aria-label="Acessível em Libras"></a>
  </div>
</div>

<div class="banner container navbar">
  <div class="navbar-header" style="width: 100%;max-width: 100%;">  
    <div class="row">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
        <span class="sr-only">Toggle navigation</span>
        <i class="fa fa-bars" aria-hidden="true"></i>
      </button>
      <div class="col-sm-4">
        <a role="logo" class="navbar-brand" href="<?=$this->url('home')?>">
          <img alt="BDTD" src="<?=$this->imageLink('BDTD15.jpg') ?>" width="100%" style="margin-top: 0.5em;">
        </a>        
      </div>
      <div class="col-sm-6" style="float: right;width: 55%">

          <? if (!isset($this->layout()->renderingError)): ?>
            <div class="collapse navbar-collapse" id="header-collapse">
              <nav>
                <ul role="navigation" class="nav navbar-nav navbar-right flip">
                  <? if ($this->feedback()->tabEnabled()): ?>
                    <li>
                      <a id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope" aria-hidden="true"></i> <?=$this->transEsc("Feedback")?></a>
                    </li>
                  <? endif; ?>
                  <? $cart = $this->cart(); if ($cart->isActive()): ?>
                    <li id="cartSummary">
                      <a id="cartItems" data-lightbox title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
                        <i class="fa fa-suitcase" aria-hidden="true"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?>
                        <span class="full<?=!$cart->isFull() ? ' hidden' : '' ?>">(<?=$this->transEsc('bookbag_full') ?>)</span>
                      </a>
                    </li>
                  <? endif; ?>
                  <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
                    <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
                      <a href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>"><i class="fa fa-home" aria-hidden="true"></i> <?=$this->transEsc("Your Account")?></a>
                    </li>
                    <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
                      <a href="<?=$this->url('myresearch-logout')?>" class="logout"><i class="fa fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?></a>
                    </li>
                    <li id="loginOptions"<? if($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
                      <? if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                        <a href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Institutional Login")?></a>
                      <? else: ?>
                        <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Login")?></a>
                      <? endif; ?>
                    </li>
           <? endif; ?>

          <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
            <li class="theme dropdown">
              <form method="post" name="themeForm" id="themeForm">
                <input type="hidden" name="ui"/>
              </form>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <? foreach ($this->layout()->themeOptions as $current): ?>
                  <li<?=$current['selected'] ? ' class="active"' : ''?>><a href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
                <? endforeach; ?>
              </ul>
            </li>
          <? endif; ?>

          <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
            <li class="language dropdown">
              <form method="post" name="langForm" id="langForm">
                <input type="hidden" name="mylang"/>
              </form>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                  <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
                <? endforeach; ?>
              </ul>
            </li>
          <? endif; ?>
        </ul>
      </nav>
    </div>
<? endif; ?> 

          <!--a class="navbar-brand lang-<?=$this->layout()->userLang ?>" href="<?=$this->url('home')?>">VuFind</a-->
        <ul class="nav navbar-nav textHeader">
          <li class="">
              <a class="external-link" href="<?=$this->url('home')?>">Página Inicial</a>          
          </li> 
          <li class="dropdown">
              <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                Institucional <b class="caret"></b>    
              </a>
              <ul class="dropdown-menu">
                <li><a href="<?=$this->url('content-page', ['page' => 'whatIs']) ?>">O que é?</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'history']) ?>">Histórico</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'howWork']) ?>">Como Funciona?</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'technology']) ?>">Tecnologias</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'patterns']) ?>">Padrões e diretrizes</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'bdtd15']) ?>">BDTD 15 anos</a></li>              
                <!--li class="divider"></li>
                <li><a href="<?=$this->url('home')?>Contents/Home?section=who">Link relacionados</a></li-->
              </ul>
          </li>  
          <li class="">
              <a class="external-link" href="/vufind/Institutions"> Instituições Participantes</a>
          </li>  
          <li class="dropdown">
              <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                Serviços <b class="caret"></b>    
              </a>
              <ul class="dropdown-menu">
                  <li><a href="<?=$this->url('content-page', ['page' => 'statics']) ?>">Indicadores</a></li>
                  <li><a href="<?=$this->url('content-page', ['page' => 'tede']) ?>">TEDE</a></li>
                  <li><a href="<?=$this->url('content-page', ['page' => 'participate']) ?>">Como participar?</a></li>
                  <li><a href="<?=$this->url('content-page', ['page' => 'access']) ?>">Instrumentos de Adesão</a></li>
                  <li><a href="<?=$this->url('content-page', ['page' => 'brasilOpen']) ?>">Acesso Aberto Brasil</a></li>
                  <li><a href="<?=$this->url('content-page', ['page' => 'contact']) ?>">Contato</a></li>
                  <li><a href="<?=$this->url('content-page', ['page' => 'faqs']) ?>">FAQ</a></li>                  
              </ul>              
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="search2 container navbar">
  <nav class="nav searchbox hidden-print">
    <?=$this->layout()->searchbox ?>
  </nav>
</div>

<script type="text/javascript">
  $('ul.nav li.dropdown').hover(function() {
      $(this).find('.dropdown-menu').stop(true, true).delay(20).fadeIn(500);
    }, 
    function() {
      $(this).find('.dropdown-menu').stop(true, true).delay(20).fadeOut(500);
    }
  );
</script>
