<div class="clearfix">&nbsp;</div>
<footer class="hidden-print">
  <div class="container">
    <div class="row">
      <div class="col-sm-4 azul1">
        <p>Godoy Cruz 2320, 4º Piso (C1425FQD)<br>Ciudad Autónoma de Buenos Aires, República Argentina<br>Tel./Fax: (+54) 11 4899-5000 int.  4232 y 4228</p>
        <p class="mailrepo"><a href="mailto:repositorios@mincyt.gob.ar">repositorios@mincyt.gob.ar</a></p>
      </div>
      <div class="col-sm-4 azul2 text-center redes-sociales">
      <p>
        <a class="socialMediaLink" href="https://www.facebook.com/ministeriodeciencia" target="_blank"><i class="fa fa-facebook-square fa-fw fa-2x" aria-hidden="true"></i></a>
        <a class="socialMediaLink" href="https://twitter.com/min_ciencia" target="_blank"><i class="fa fa-twitter-square fa-fw fa-2x" aria-hidden="true"></i></a>
        <a class="socialMediaLink" href="https://www.flickr.com/photos/ministeriodeciencia" target="_blank"><i class="fa fa-flickr fa-fw fa-2x" aria-hidden="true"></i></a>
        <a class="socialMediaLink" href="https://plus.google.com/+MinisterioDeCienciaArgentina" target="_blank"><i class="fa fa-google-plus-square fa-fw fa-2x" aria-hidden="true"></i></a>
        <a class="socialMediaLink" href="https://www.instagram.com/min_ciencia" target="_blank"><i class="fa fa-instagram fa-fw fa-2x" aria-hidden="true"></i></a>
        <a class="socialMediaLink" href="https://www.youtube.com/ministeriodecienciaargentina" target="_blank"><i class="fa fa-youtube-square fa-fw fa-2x" aria-hidden="true"></i></a>
        <a class="socialMediaLink" href="https://ar.linkedin.com/company/ministerio-de-ciencia-tecnolog-a-e-innovaci-n-productiva" target="_blank"><i class="fa fa-linkedin-square fa-fw fa-2x" aria-hidden="true"></i></a>
      </p>
      </div>
      <div class="col-sm-4 azul1 logo-mincyt">
        <a href="http://www.mincyt.gob.ar/" target="_blank"><img src="<?=$this->imageLink('Logo_Ministerio_NegativoTranparencia.png') ?>" alt="Logo MINCYT" /></a>
      </div>
    </div>
    </div>
</footer>
