<h1 class="page-header">INSTITUCIONAL</h1>

<p class="text-justify" style="color:#000;" >Acceso a la Ciencia y la Cultura de El Salvador - ACCES tiene por finalidad propiciar el trabajo colaborativo de instituciones de educación superior (IES), Centros de Investigación, instituciones de gobierno y organismos no gubernamentales, con la finalidad de integrar, difundir, preservar y dar visibilidad a su producción científica, académica y documental,  además, incorporarse a redes o directorios de repositorios internacionales para fomentar la colaboración  y apoyar el acceso abierto a contenidos académicos, científicos, culturales e históricos creados en El Salvador.</p>

<h2 class="h2" >¿Quiénes somos?</h2>

<p class="text-justify" style="color:#000;">Acceso a la Ciencia y la Cultura de El Salvador - ACCES está integrada por los repositorios de las instituciones miembros del Consorcio de Bibliotecas Universitarias de El Salvador <a href="http://www.cbues.org.sv/"> CBUES. </a></p>

<h2 class="h2">¿Cómo participar?</h2>

<p class="text-justify" style="color:#000;">Pueden adherirse, como miembros de la red, cualquier institución con un repositorio institucional que adopte las directrices de ACCES o aquellas instituciones que cuenten con una comunidad institucional en el Repositorio Digital de Ciencia y Cultura de El Salvador REDICCES y compartan documentos académicos, científicos o de patrimonio cultural.</p>


<h2 class="h2">Acceso Abierto </h2>

<p class="text-justify" style="color:#000;">“Acceso Abierto a las publicaciones científicas significa que cualquier individuo interesado en esta literatura pueda leer, descargar, copiar, distribuir, imprimir, buscar o enlazar los textos completos y usarlos con cualquier propósito legítimo, de manera libre y abierta. La única restricción del Acceso Abierto está en otorgarle a los autores el respeto a la integridad de su trabajo y el derecho a ser adecuadamente reconocidos y citados.” (Declaración de Acceso Abierto de Budapest, 2002)</p>

<h2 class="h2">¿Cómo lo hacemos?</h2>

<p class="text-justify" style="color:#000;">Trabajamos previamente en procesos organizativos y técnicos que garantizan la calidad de los datos, centrándonos en varias fases:</p>


<h3 class="h3">Acordamos</h3>

<p class="text-justify" style="color:#000;">Los integrantes suscriben acuerdos para definir políticas comunes y estándares de calidad con el objetivo de construir una red nacional de repositorios en acceso abierto.</p>

<h3 class="h3">Cosechamos</h3>

<p class="text-justify" style="color:#000;">Periódicamente recolectamos los registros de metadatos ofrecidos por los repositorios, manteniendo actualizados los contenidos ofrecidos en el portal.</p>

<h3 class="h3">Validamos</h3>

<p class="text-justify" style="color:#000;">Generamos mecanismos para asegurar la calidad de la información publicada, de acuerdo con las directrices de calidad acordadas con los miembros de ACCES.</p>


<h3 class="h3">Federamos</h3>

<p class="text-justify" style="color:#000;">Realizamos un proceso de integración e indexación de los contenidos recolectados de los diferentes repositorios, facilitando a los usuarios un servicio de búsqueda unificado de todos los contenidos producidos en El Salvador.</p>


<h3 class="h3">Ofrecemos</h3>

<p class="text-justify" style="color:#000;">En el portal público de búsqueda, facilitamos la recuperación de la información y el acceso al texto completo en acceso abierto en el repositorio institucional original. Se ofrece un sistema de estadísticas sobre los contenidos y su impacto. Un proveedor OAI-PMH unificado permite la cosecha de los registros de la red, maximizando la visibilidad global de los contenidos producidos en El Salvador</p>

<br>
<h2 class="h2">Contacto</h2>

<p style="color:#0000FF;"> <a href="http://www.lareferencia.info/joomla/es/">Red de Repositorios en Acceso Abierto LA Referencia </a> </p>
<p style="color:#0000FF;"> <a href="http://www.udb.edu.sv/">Universidad Don Bosco UDB</a> </p>
<p style="color:#0000FF;"> <a href="http://www.catolica.edu.sv/">Universidad Católica de El Salvador (UNICAES)</a> </p>
<p style="color:#0000FF;"> <a href="http://www.uca.edu.sv/">Universidad Centroamericana “José Simeón Cañas” UCA</a> </p>
<p class="text-justify" style="color:#000;">Para más información sobre el proyecto:
<br>Teléfono: +503 2210 6600 Ext. 304
<br>Correo electrónico: ccienfuegos@uca.edu.sv 
</p>
