<div class="clearfix">&nbsp;</div>
<footer class="hidden-print">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 footer-contact">
        <p>Aquí los datos de contacto. Dirección postal, etc.</p>
      </div>
      <div class="col-sm-4 text-center social-media">
      <p>
        <a class="socialMediaLink" href="#" target="_blank"><i class="fa fa-facebook-square fa-fw fa-2x" aria-hidden="true"></i></a>
        <a class="socialMediaLink" href="#" target="_blank"><i class="fa fa-twitter-square fa-fw fa-2x" aria-hidden="true"></i></a>
        <a class="socialMediaLink" href="#" target="_blank"><i class="fa fa-flickr fa-fw fa-2x" aria-hidden="true"></i></a>
        <a class="socialMediaLink" href="#" target="_blank"><i class="fa fa-google-plus-square fa-fw fa-2x" aria-hidden="true"></i></a>
        <a class="socialMediaLink" href="#" target="_blank"><i class="fa fa-instagram fa-fw fa-2x" aria-hidden="true"></i></a>
        <a class="socialMediaLink" href="#" target="_blank"><i class="fa fa-youtube-square fa-fw fa-2x" aria-hidden="true"></i></a>
        <a class="socialMediaLink" href="#" target="_blank"><i class="fa fa-linkedin-square fa-fw fa-2x" aria-hidden="true"></i></a>
      </p>
      </div>
    </div>
  </div>
</footer>
